// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inapi/app.proto

package inapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// host
type AppSpecDepend struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Priority             int32    `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	Configs              []string `protobuf:"bytes,5,rep,name=configs" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSpecDepend) Reset()         { *m = AppSpecDepend{} }
func (m *AppSpecDepend) String() string { return proto.CompactTextString(m) }
func (*AppSpecDepend) ProtoMessage()    {}
func (*AppSpecDepend) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_a6d2baf93302db4b, []int{0}
}
func (m *AppSpecDepend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSpecDepend.Unmarshal(m, b)
}
func (m *AppSpecDepend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSpecDepend.Marshal(b, m, deterministic)
}
func (dst *AppSpecDepend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSpecDepend.Merge(dst, src)
}
func (m *AppSpecDepend) XXX_Size() int {
	return xxx_messageInfo_AppSpecDepend.Size(m)
}
func (m *AppSpecDepend) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSpecDepend.DiscardUnknown(m)
}

var xxx_messageInfo_AppSpecDepend proto.InternalMessageInfo

func (m *AppSpecDepend) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppSpecDepend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppSpecDepend) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppSpecDepend) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AppSpecDepend) GetConfigs() []string {
	if m != nil {
		return m.Configs
	}
	return nil
}

type AppServiceReplica struct {
	Rep                  uint32   `protobuf:"varint,1,opt,name=rep" json:"rep,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppServiceReplica) Reset()         { *m = AppServiceReplica{} }
func (m *AppServiceReplica) String() string { return proto.CompactTextString(m) }
func (*AppServiceReplica) ProtoMessage()    {}
func (*AppServiceReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_a6d2baf93302db4b, []int{1}
}
func (m *AppServiceReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServiceReplica.Unmarshal(m, b)
}
func (m *AppServiceReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServiceReplica.Marshal(b, m, deterministic)
}
func (dst *AppServiceReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServiceReplica.Merge(dst, src)
}
func (m *AppServiceReplica) XXX_Size() int {
	return xxx_messageInfo_AppServiceReplica.Size(m)
}
func (m *AppServiceReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServiceReplica.DiscardUnknown(m)
}

var xxx_messageInfo_AppServiceReplica proto.InternalMessageInfo

func (m *AppServiceReplica) GetRep() uint32 {
	if m != nil {
		return m.Rep
	}
	return 0
}

func (m *AppServiceReplica) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AppServiceReplica) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type AppServicePort struct {
	Port                 uint32               `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
	Endpoints            []*AppServiceReplica `protobuf:"bytes,2,rep,name=endpoints" json:"endpoints,omitempty"`
	Updated              int64                `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Spec                 string               `protobuf:"bytes,6,opt,name=spec" json:"spec,omitempty"`
	PodId                string               `protobuf:"bytes,7,opt,name=pod_id,json=podId" json:"pod_id,omitempty"`
	AppId                string               `protobuf:"bytes,8,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppServicePort) Reset()         { *m = AppServicePort{} }
func (m *AppServicePort) String() string { return proto.CompactTextString(m) }
func (*AppServicePort) ProtoMessage()    {}
func (*AppServicePort) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_a6d2baf93302db4b, []int{2}
}
func (m *AppServicePort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServicePort.Unmarshal(m, b)
}
func (m *AppServicePort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServicePort.Marshal(b, m, deterministic)
}
func (dst *AppServicePort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServicePort.Merge(dst, src)
}
func (m *AppServicePort) XXX_Size() int {
	return xxx_messageInfo_AppServicePort.Size(m)
}
func (m *AppServicePort) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServicePort.DiscardUnknown(m)
}

var xxx_messageInfo_AppServicePort proto.InternalMessageInfo

func (m *AppServicePort) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AppServicePort) GetEndpoints() []*AppServiceReplica {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *AppServicePort) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AppServicePort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppServicePort) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *AppServicePort) GetPodId() string {
	if m != nil {
		return m.PodId
	}
	return ""
}

func (m *AppServicePort) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppServicePortPodBind struct {
	Port                 uint32               `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
	PodId                string               `protobuf:"bytes,2,opt,name=pod_id,json=podId" json:"pod_id,omitempty"`
	Endpoints            []*AppServiceReplica `protobuf:"bytes,3,rep,name=endpoints" json:"endpoints,omitempty"`
	Updated              int64                `protobuf:"varint,4,opt,name=updated" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppServicePortPodBind) Reset()         { *m = AppServicePortPodBind{} }
func (m *AppServicePortPodBind) String() string { return proto.CompactTextString(m) }
func (*AppServicePortPodBind) ProtoMessage()    {}
func (*AppServicePortPodBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_a6d2baf93302db4b, []int{3}
}
func (m *AppServicePortPodBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServicePortPodBind.Unmarshal(m, b)
}
func (m *AppServicePortPodBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServicePortPodBind.Marshal(b, m, deterministic)
}
func (dst *AppServicePortPodBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServicePortPodBind.Merge(dst, src)
}
func (m *AppServicePortPodBind) XXX_Size() int {
	return xxx_messageInfo_AppServicePortPodBind.Size(m)
}
func (m *AppServicePortPodBind) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServicePortPodBind.DiscardUnknown(m)
}

var xxx_messageInfo_AppServicePortPodBind proto.InternalMessageInfo

func (m *AppServicePortPodBind) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AppServicePortPodBind) GetPodId() string {
	if m != nil {
		return m.PodId
	}
	return ""
}

func (m *AppServicePortPodBind) GetEndpoints() []*AppServiceReplica {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *AppServicePortPodBind) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type AppServicePod struct {
	PodId                string            `protobuf:"bytes,1,opt,name=pod_id,json=podId" json:"pod_id,omitempty"`
	Ports                []*AppServicePort `protobuf:"bytes,4,rep,name=ports" json:"ports,omitempty"`
	Updated              int64             `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppServicePod) Reset()         { *m = AppServicePod{} }
func (m *AppServicePod) String() string { return proto.CompactTextString(m) }
func (*AppServicePod) ProtoMessage()    {}
func (*AppServicePod) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_a6d2baf93302db4b, []int{4}
}
func (m *AppServicePod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServicePod.Unmarshal(m, b)
}
func (m *AppServicePod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServicePod.Marshal(b, m, deterministic)
}
func (dst *AppServicePod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServicePod.Merge(dst, src)
}
func (m *AppServicePod) XXX_Size() int {
	return xxx_messageInfo_AppServicePod.Size(m)
}
func (m *AppServicePod) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServicePod.DiscardUnknown(m)
}

var xxx_messageInfo_AppServicePod proto.InternalMessageInfo

func (m *AppServicePod) GetPodId() string {
	if m != nil {
		return m.PodId
	}
	return ""
}

func (m *AppServicePod) GetPorts() []*AppServicePort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *AppServicePod) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterType((*AppSpecDepend)(nil), "inapi.AppSpecDepend")
	proto.RegisterType((*AppServiceReplica)(nil), "inapi.AppServiceReplica")
	proto.RegisterType((*AppServicePort)(nil), "inapi.AppServicePort")
	proto.RegisterType((*AppServicePortPodBind)(nil), "inapi.AppServicePortPodBind")
	proto.RegisterType((*AppServicePod)(nil), "inapi.AppServicePod")
}

func init() { proto.RegisterFile("inapi/app.proto", fileDescriptor_app_a6d2baf93302db4b) }

var fileDescriptor_app_a6d2baf93302db4b = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x4b, 0x3b, 0x31,
	0x10, 0xc6, 0xc9, 0xbe, 0xf4, 0x25, 0x7f, 0xda, 0xbf, 0x06, 0x0a, 0xc1, 0xd3, 0xb2, 0xa7, 0x82,
	0x50, 0x41, 0xc1, 0xbb, 0xe2, 0xa5, 0xb7, 0x12, 0x3f, 0x80, 0xc4, 0x9d, 0x28, 0x03, 0x36, 0x19,
	0xb2, 0x6b, 0xc1, 0xb3, 0x5f, 0xc1, 0x8f, 0xe5, 0x87, 0x92, 0x64, 0xdb, 0xee, 0x2e, 0xf5, 0xe4,
	0x6d, 0xe6, 0x61, 0x32, 0xcf, 0xef, 0x19, 0xc2, 0xff, 0xa3, 0xd5, 0x84, 0x57, 0x9a, 0x68, 0x45,
	0xde, 0x35, 0x4e, 0xe4, 0x51, 0x28, 0x3f, 0x19, 0x9f, 0xdd, 0x11, 0x3d, 0x92, 0xa9, 0x1e, 0x0c,
	0x19, 0x0b, 0x62, 0xce, 0x13, 0x04, 0xc9, 0x0a, 0xb6, 0x9c, 0xaa, 0x04, 0x41, 0x08, 0x9e, 0x59,
	0xbd, 0x35, 0x32, 0x89, 0x4a, 0xac, 0x85, 0xe4, 0xe3, 0x9d, 0xf1, 0x35, 0x3a, 0x2b, 0xd3, 0x28,
	0x1f, 0x5a, 0x71, 0xc1, 0x27, 0xe4, 0xd1, 0x79, 0x6c, 0x3e, 0x64, 0x56, 0xb0, 0x65, 0xae, 0x8e,
	0x7d, 0x78, 0x55, 0x39, 0xfb, 0x82, 0xaf, 0xb5, 0xcc, 0x8b, 0x34, 0xbc, 0xda, 0xb7, 0xe5, 0x9a,
	0x9f, 0x07, 0x08, 0xe3, 0x77, 0x58, 0x19, 0x65, 0xe8, 0x0d, 0x2b, 0x2d, 0xce, 0x78, 0xea, 0x0d,
	0x45, 0x92, 0x99, 0x0a, 0x65, 0x44, 0xa3, 0x3d, 0x48, 0x82, 0x14, 0xd0, 0xc8, 0xf9, 0x26, 0x32,
	0xcc, 0x54, 0xac, 0xcb, 0x6f, 0xc6, 0xe7, 0xdd, 0xae, 0x8d, 0xf3, 0xcd, 0x71, 0x8c, 0x75, 0x63,
	0xe2, 0x96, 0x4f, 0x8d, 0x05, 0x72, 0x68, 0x9b, 0x5a, 0x26, 0x45, 0xba, 0xfc, 0x77, 0x2d, 0x57,
	0xf1, 0x24, 0xab, 0x13, 0x12, 0xd5, 0x8d, 0x86, 0x0c, 0xef, 0x04, 0xba, 0x31, 0x10, 0x5d, 0x53,
	0x75, 0x68, 0x8f, 0x77, 0xca, 0x7b, 0x77, 0x12, 0x3c, 0xab, 0xc9, 0x54, 0x72, 0xd4, 0x6a, 0xa1,
	0x16, 0x0b, 0x3e, 0x22, 0x07, 0x4f, 0x08, 0x72, 0x1c, 0xd5, 0x9c, 0x1c, 0xac, 0x21, 0xc8, 0x9a,
	0x28, 0xc8, 0x93, 0x56, 0xd6, 0x44, 0x6b, 0x28, 0xbf, 0x18, 0x5f, 0x0c, 0xe3, 0x6c, 0x1c, 0xdc,
	0xa3, 0x85, 0x5f, 0x53, 0x75, 0xbb, 0x93, 0xfe, 0xee, 0x41, 0xd8, 0xf4, 0x4f, 0x61, 0xb3, 0x41,
	0xd8, 0x72, 0xdb, 0xfe, 0x9a, 0x03, 0x15, 0xf4, 0x9c, 0x59, 0xdf, 0xf9, 0x92, 0xe7, 0x01, 0xac,
	0x96, 0x59, 0x74, 0x5d, 0x9c, 0xb8, 0x86, 0x44, 0xaa, 0x9d, 0xe9, 0xdb, 0xe5, 0x03, 0xbb, 0xe7,
	0x51, 0xfc, 0xb3, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xe4, 0x6b, 0x23, 0xc6, 0x02,
	0x00, 0x00,
}
