// Code generated by protoc-gen-go.
// source: inapi/base.proto
// DO NOT EDIT!

/*
Package inapi is a generated protocol buffer package.

It is generated from these files:
	inapi/base.proto
	inapi/cluster.proto
	inapi/pod.proto

It has these top-level messages:
	ErrorMeta
	TypeMeta
	ObjectMeta
	Label
	ResHostOperate
	ResHost
	ResHostList
	ResHostSpec
	ResPlatform
	ResHostResource
	ResHostStatus
	ResZone
	ResCell
	ResZoneMasterNode
	ResZoneMasterList
	PbPodRepStatus
	PbVolumeMount
	PbServicePort
	PbPodBoxStatusExecutor
	PbPodBoxStatus
	PbOpLogSets
	PbOpLogEntry
*/
package inapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorMeta struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorMeta) Reset()                    { *m = ErrorMeta{} }
func (m *ErrorMeta) String() string            { return proto.CompactTextString(m) }
func (*ErrorMeta) ProtoMessage()               {}
func (*ErrorMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorMeta) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorMeta) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TypeMeta struct {
	KindJ string     `protobuf:"bytes,1,opt,name=kind_j,json=kindJ" json:"kind_j,omitempty"`
	Error *ErrorMeta `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *TypeMeta) Reset()                    { *m = TypeMeta{} }
func (m *TypeMeta) String() string            { return proto.CompactTextString(m) }
func (*TypeMeta) ProtoMessage()               {}
func (*TypeMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeMeta) GetKindJ() string {
	if m != nil {
		return m.KindJ
	}
	return ""
}

func (m *TypeMeta) GetError() *ErrorMeta {
	if m != nil {
		return m.Error
	}
	return nil
}

type ObjectMeta struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Created uint64 `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Updated uint64 `protobuf:"varint,4,opt,name=updated" json:"updated,omitempty"`
}

func (m *ObjectMeta) Reset()                    { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string            { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()               {}
func (*ObjectMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ObjectMeta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMeta) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ObjectMeta) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Label struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorMeta)(nil), "inapi.ErrorMeta")
	proto.RegisterType((*TypeMeta)(nil), "inapi.TypeMeta")
	proto.RegisterType((*ObjectMeta)(nil), "inapi.ObjectMeta")
	proto.RegisterType((*Label)(nil), "inapi.Label")
}

func init() { proto.RegisterFile("inapi/base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x75, 0x53, 0xed, 0x08, 0x52, 0x82, 0x42, 0x8e, 0x25, 0x07, 0xe9, 0x69, 0x45,
	0x3d, 0xf9, 0x03, 0x3c, 0x28, 0x8a, 0xb0, 0x78, 0x97, 0xc9, 0x66, 0x90, 0xd4, 0x76, 0x13, 0xb2,
	0xa9, 0xe0, 0xbf, 0x97, 0xcc, 0x6e, 0x4a, 0x6f, 0xf3, 0xe6, 0xf1, 0xbe, 0x37, 0x0c, 0xac, 0xdc,
	0x80, 0xc1, 0xdd, 0x19, 0x1c, 0xa9, 0x0d, 0xd1, 0x27, 0x2f, 0x05, 0x6f, 0xf4, 0x13, 0x2c, 0x9f,
	0x63, 0xf4, 0xf1, 0x9d, 0x12, 0x4a, 0x09, 0x4d, 0xef, 0x2d, 0xa9, 0x6a, 0x5d, 0x6d, 0x96, 0x1d,
	0xcf, 0x52, 0xc1, 0xf9, 0x9e, 0xc6, 0x11, 0xbf, 0x49, 0xd5, 0xbc, 0x2e, 0x52, 0xbf, 0xc0, 0xc5,
	0xe7, 0x5f, 0x20, 0x4e, 0xde, 0xc0, 0xe2, 0xc7, 0x0d, 0xf6, 0x6b, 0x3b, 0x67, 0x45, 0x56, 0xaf,
	0xf2, 0x16, 0x04, 0x65, 0x3a, 0x47, 0x2f, 0x1f, 0x56, 0x2d, 0x97, 0xb6, 0xc7, 0xc6, 0x6e, 0xb2,
	0xb5, 0x05, 0xf8, 0x30, 0x5b, 0xea, 0x13, 0xc3, 0xae, 0xa0, 0x76, 0x76, 0x06, 0xd5, 0xce, 0xe6,
	0xb3, 0x06, 0xdc, 0x97, 0x7e, 0x9e, 0xf3, 0x59, 0x7d, 0x24, 0x4c, 0x64, 0xd5, 0xd9, 0xba, 0xda,
	0x34, 0x5d, 0x91, 0xd9, 0x39, 0x04, 0xcb, 0x4e, 0x33, 0x39, 0xb3, 0xd4, 0xf7, 0x20, 0xde, 0xd0,
	0xd0, 0xee, 0x08, 0xac, 0x4e, 0x80, 0xd7, 0x20, 0x7e, 0x71, 0x77, 0x28, 0x2d, 0x93, 0x30, 0x0b,
	0x7e, 0xd6, 0xe3, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xb9, 0x81, 0xf9, 0x40, 0x01, 0x00,
	0x00,
}
