// Code generated by github.com/hooto/protobuf_slice
// source: base.proto
// DO NOT EDIT!

package inapi

import "sync"

var object_slice_mu_Label sync.RWMutex

func (it *Label) Equal(it2 *Label) bool {
	if it2 == nil ||
		it.Name != it2.Name ||
		it.Value != it2.Value {
		return false
	}
	return true
}

func (it *Label) Sync(it2 *Label) bool {
	if it2 == nil {
		return false
	}
	changed := false
	if it.Name != it2.Name {
		it.Name, changed = it2.Name, true
	}
	if it.Value != it2.Value {
		it.Value, changed = it2.Value, true
	}
	return changed
}

func LabelSliceGet(ls []*Label, arg_name string) *Label {
	object_slice_mu_Label.RLock()
	defer object_slice_mu_Label.RUnlock()

	for _, v := range ls {
		if v.Name == arg_name {
			return v
		}
	}
	return nil
}

func LabelSliceEqual(ls, ls2 []*Label) bool {
	object_slice_mu_Label.RLock()
	defer object_slice_mu_Label.RUnlock()

	if len(ls) != len(ls2) {
		return false
	}
	hit := false
	for _, v := range ls {
		hit = false
		for _, v2 := range ls2 {
			if v.Name != v2.Name {
				continue
			}
			if v.Value != v2.Value {
				return false
			}
			hit = true
			break
		}
		if !hit {
			return false
		}
	}
	return true
}

func LabelSliceSync(ls []*Label, it2 *Label) ([]*Label, bool) {
	if it2 == nil {
		return ls, false
	}
	object_slice_mu_Label.Lock()
	defer object_slice_mu_Label.Unlock()

	hit := false
	changed := false
	for _, v := range ls {
		if v.Name != it2.Name {
			continue
		}
		if v.Value != it2.Value {
			v.Value, changed = it2.Value, true
		}
		hit = true
		break
	}
	if !hit {
		ls = append(ls, it2)
		changed = true
	}
	return ls, changed
}

func LabelSliceSyncSlice(ls, ls2 []*Label) ([]*Label, bool) {
	if len(ls2) == 0 {
		return ls, false
	}
	object_slice_mu_Label.Lock()
	defer object_slice_mu_Label.Unlock()

	hit := false
	changed := false
	for _, v2 := range ls2 {
		hit = false
		for _, v := range ls {
			if v.Name != v2.Name {
				continue
			}
			if v.Value != v2.Value {
				v.Value, changed = v2.Value, true
			}
			hit = true
			break
		}
		if !hit {
			ls = append(ls, v2)
			changed = true
		}
	}
	return ls, changed
}
