// Code generated by protoc-gen-go.
// source: inapi/cluster.proto
// DO NOT EDIT!

package inapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// host
type ResHostOperate struct {
	Action   uint32   `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	CellId   string   `protobuf:"bytes,2,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	ZoneId   string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CpuUsed  int64    `protobuf:"varint,4,opt,name=cpu_used,json=cpuUsed" json:"cpu_used,omitempty"`
	MemUsed  int64    `protobuf:"varint,5,opt,name=mem_used,json=memUsed" json:"mem_used,omitempty"`
	LssUsed  int64    `protobuf:"varint,6,opt,name=lss_used,json=lssUsed" json:"lss_used,omitempty"`
	PortUsed []uint32 `protobuf:"varint,7,rep,packed,name=port_used,json=portUsed" json:"port_used,omitempty"`
}

func (m *ResHostOperate) Reset()                    { *m = ResHostOperate{} }
func (m *ResHostOperate) String() string            { return proto.CompactTextString(m) }
func (*ResHostOperate) ProtoMessage()               {}
func (*ResHostOperate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ResHostOperate) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostOperate) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostOperate) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostOperate) GetCpuUsed() int64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *ResHostOperate) GetMemUsed() int64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *ResHostOperate) GetLssUsed() int64 {
	if m != nil {
		return m.LssUsed
	}
	return 0
}

func (m *ResHostOperate) GetPortUsed() []uint32 {
	if m != nil {
		return m.PortUsed
	}
	return nil
}

type ResHost struct {
	Meta    *ObjectMeta       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Operate *ResHostOperate   `protobuf:"bytes,2,opt,name=operate" json:"operate,omitempty"`
	Spec    *ResHostSpec      `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status  *ResHostStatus    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Prs     []*PbPodRepStatus `protobuf:"bytes,5,rep,name=prs" json:"prs,omitempty"`
}

func (m *ResHost) Reset()                    { *m = ResHost{} }
func (m *ResHost) String() string            { return proto.CompactTextString(m) }
func (*ResHost) ProtoMessage()               {}
func (*ResHost) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ResHost) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResHost) GetOperate() *ResHostOperate {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *ResHost) GetSpec() *ResHostSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ResHost) GetStatus() *ResHostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ResHost) GetPrs() []*PbPodRepStatus {
	if m != nil {
		return m.Prs
	}
	return nil
}

type ResHostList struct {
	Items []*ResHost `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *ResHostList) Reset()                    { *m = ResHostList{} }
func (m *ResHostList) String() string            { return proto.CompactTextString(m) }
func (*ResHostList) ProtoMessage()               {}
func (*ResHostList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ResHostList) GetItems() []*ResHost {
	if m != nil {
		return m.Items
	}
	return nil
}

type ResHostSpec struct {
	Platform    *ResPlatform     `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Capacity    *ResHostResource `protobuf:"bytes,3,opt,name=capacity" json:"capacity,omitempty"`
	HttpPort    uint32           `protobuf:"varint,5,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
	PeerLanAddr string           `protobuf:"bytes,6,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	PeerWanAddr string           `protobuf:"bytes,7,opt,name=peer_wan_addr,json=peerWanAddr" json:"peer_wan_addr,omitempty"`
}

func (m *ResHostSpec) Reset()                    { *m = ResHostSpec{} }
func (m *ResHostSpec) String() string            { return proto.CompactTextString(m) }
func (*ResHostSpec) ProtoMessage()               {}
func (*ResHostSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ResHostSpec) GetPlatform() *ResPlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ResHostSpec) GetCapacity() *ResHostResource {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *ResHostSpec) GetHttpPort() uint32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ResHostSpec) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostSpec) GetPeerWanAddr() string {
	if m != nil {
		return m.PeerWanAddr
	}
	return ""
}

type ResPlatform struct {
	Os     string `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Kernel string `protobuf:"bytes,2,opt,name=kernel" json:"kernel,omitempty"`
	Arch   string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
}

func (m *ResPlatform) Reset()                    { *m = ResPlatform{} }
func (m *ResPlatform) String() string            { return proto.CompactTextString(m) }
func (*ResPlatform) ProtoMessage()               {}
func (*ResPlatform) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ResPlatform) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ResPlatform) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *ResPlatform) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ResHostResource struct {
	Mem  uint64           `protobuf:"varint,1,opt,name=mem" json:"mem,omitempty"`
	Cpu  uint64           `protobuf:"varint,2,opt,name=cpu" json:"cpu,omitempty"`
	Vols []*ResHostVolume `protobuf:"bytes,3,rep,name=vols" json:"vols,omitempty"`
}

func (m *ResHostResource) Reset()                    { *m = ResHostResource{} }
func (m *ResHostResource) String() string            { return proto.CompactTextString(m) }
func (*ResHostResource) ProtoMessage()               {}
func (*ResHostResource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ResHostResource) GetMem() uint64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

func (m *ResHostResource) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ResHostResource) GetVols() []*ResHostVolume {
	if m != nil {
		return m.Vols
	}
	return nil
}

type ResHostVolume struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Total uint64 `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Used  uint64 `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
}

func (m *ResHostVolume) Reset()                    { *m = ResHostVolume{} }
func (m *ResHostVolume) String() string            { return proto.CompactTextString(m) }
func (*ResHostVolume) ProtoMessage()               {}
func (*ResHostVolume) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ResHostVolume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResHostVolume) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResHostVolume) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type ResHostStatus struct {
	Phase  string             `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	Uptime uint32             `protobuf:"varint,2,opt,name=uptime" json:"uptime,omitempty"`
	Stats  *PbStatsSampleFeed `protobuf:"bytes,3,opt,name=stats" json:"stats,omitempty"`
}

func (m *ResHostStatus) Reset()                    { *m = ResHostStatus{} }
func (m *ResHostStatus) String() string            { return proto.CompactTextString(m) }
func (*ResHostStatus) ProtoMessage()               {}
func (*ResHostStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ResHostStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *ResHostStatus) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *ResHostStatus) GetStats() *PbStatsSampleFeed {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ResZone struct {
	Meta     *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Phase    int32       `protobuf:"varint,3,opt,name=phase" json:"phase,omitempty"`
	Summary  string      `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	WanAddrs []string    `protobuf:"bytes,5,rep,name=wan_addrs,json=wanAddrs" json:"wan_addrs,omitempty"`
	LanAddrs []string    `protobuf:"bytes,6,rep,name=lan_addrs,json=lanAddrs" json:"lan_addrs,omitempty"`
	Cells    []*ResCell  `protobuf:"bytes,7,rep,name=cells" json:"cells,omitempty"`
	Options  []*Label    `protobuf:"bytes,8,rep,name=options" json:"options,omitempty"`
}

func (m *ResZone) Reset()                    { *m = ResZone{} }
func (m *ResZone) String() string            { return proto.CompactTextString(m) }
func (*ResZone) ProtoMessage()               {}
func (*ResZone) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ResZone) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResZone) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResZone) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ResZone) GetWanAddrs() []string {
	if m != nil {
		return m.WanAddrs
	}
	return nil
}

func (m *ResZone) GetLanAddrs() []string {
	if m != nil {
		return m.LanAddrs
	}
	return nil
}

func (m *ResZone) GetCells() []*ResCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *ResZone) GetOptions() []*Label {
	if m != nil {
		return m.Options
	}
	return nil
}

type ResCell struct {
	Meta        *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	ZoneId      string      `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Phase       int32       `protobuf:"varint,4,opt,name=phase" json:"phase,omitempty"`
	Description string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *ResCell) Reset()                    { *m = ResCell{} }
func (m *ResCell) String() string            { return proto.CompactTextString(m) }
func (*ResCell) ProtoMessage()               {}
func (*ResCell) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ResCell) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResCell) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResCell) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResCell) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ResZoneMasterNode struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addr   string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Action uint32 `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
}

func (m *ResZoneMasterNode) Reset()                    { *m = ResZoneMasterNode{} }
func (m *ResZoneMasterNode) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterNode) ProtoMessage()               {}
func (*ResZoneMasterNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ResZoneMasterNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResZoneMasterNode) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ResZoneMasterNode) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ResZoneMasterList struct {
	Version uint64               `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Leader  string               `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	Updated uint64               `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Items   []*ResZoneMasterNode `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *ResZoneMasterList) Reset()                    { *m = ResZoneMasterList{} }
func (m *ResZoneMasterList) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterList) ProtoMessage()               {}
func (*ResZoneMasterList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ResZoneMasterList) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResZoneMasterList) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *ResZoneMasterList) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ResZoneMasterList) GetItems() []*ResZoneMasterNode {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ResHostOperate)(nil), "inapi.ResHostOperate")
	proto.RegisterType((*ResHost)(nil), "inapi.ResHost")
	proto.RegisterType((*ResHostList)(nil), "inapi.ResHostList")
	proto.RegisterType((*ResHostSpec)(nil), "inapi.ResHostSpec")
	proto.RegisterType((*ResPlatform)(nil), "inapi.ResPlatform")
	proto.RegisterType((*ResHostResource)(nil), "inapi.ResHostResource")
	proto.RegisterType((*ResHostVolume)(nil), "inapi.ResHostVolume")
	proto.RegisterType((*ResHostStatus)(nil), "inapi.ResHostStatus")
	proto.RegisterType((*ResZone)(nil), "inapi.ResZone")
	proto.RegisterType((*ResCell)(nil), "inapi.ResCell")
	proto.RegisterType((*ResZoneMasterNode)(nil), "inapi.ResZoneMasterNode")
	proto.RegisterType((*ResZoneMasterList)(nil), "inapi.ResZoneMasterList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiZoneMaster service

type ApiZoneMasterClient interface {
	HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResZoneMasterList, error)
}

type apiZoneMasterClient struct {
	cc *grpc.ClientConn
}

func NewApiZoneMasterClient(cc *grpc.ClientConn) ApiZoneMasterClient {
	return &apiZoneMasterClient{cc}
}

func (c *apiZoneMasterClient) HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResZoneMasterList, error) {
	out := new(ResZoneMasterList)
	err := grpc.Invoke(ctx, "/inapi.ApiZoneMaster/HostStatusSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiZoneMaster service

type ApiZoneMasterServer interface {
	HostStatusSync(context.Context, *ResHost) (*ResZoneMasterList, error)
}

func RegisterApiZoneMasterServer(s *grpc.Server, srv ApiZoneMasterServer) {
	s.RegisterService(&_ApiZoneMaster_serviceDesc, srv)
}

func _ApiZoneMaster_HostStatusSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inapi.ApiZoneMaster/HostStatusSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, req.(*ResHost))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiZoneMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ApiZoneMaster",
	HandlerType: (*ApiZoneMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostStatusSync",
			Handler:    _ApiZoneMaster_HostStatusSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inapi/cluster.proto",
}

func init() { proto.RegisterFile("inapi/cluster.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 844 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x8e, 0xe4, 0x34,
	0x10, 0xa6, 0x3b, 0xe9, 0x3f, 0x37, 0x3d, 0xbb, 0x63, 0x96, 0x25, 0x0c, 0x97, 0x56, 0xb4, 0x2c,
	0x7d, 0x40, 0xbd, 0x52, 0xef, 0x95, 0xcb, 0x0a, 0x09, 0x31, 0xd2, 0x0c, 0xd3, 0xf2, 0x08, 0x90,
	0xb8, 0xb4, 0xdc, 0x71, 0xa1, 0x09, 0x38, 0xb1, 0x15, 0x3b, 0xbb, 0x1a, 0x6e, 0x3c, 0x01, 0xaf,
	0xc5, 0x13, 0x70, 0xe6, 0xc8, 0x63, 0xa0, 0x2a, 0x3b, 0xe9, 0x1f, 0x01, 0xe2, 0x96, 0xaa, 0xef,
	0x73, 0xd9, 0x5f, 0xfd, 0x85, 0x7d, 0x50, 0xd6, 0xd2, 0x96, 0xaf, 0x0a, 0xdd, 0x3a, 0x0f, 0xcd,
	0xda, 0x36, 0xc6, 0x1b, 0x3e, 0x22, 0xe7, 0xd5, 0xd3, 0x80, 0xed, 0xa5, 0x83, 0x00, 0x5c, 0x3d,
	0x09, 0x1e, 0x6b, 0x54, 0x74, 0x5c, 0x06, 0x87, 0xf3, 0xd2, 0xbb, 0xe0, 0xca, 0x7f, 0x1f, 0xb0,
	0x0b, 0x01, 0xee, 0x6b, 0xe3, 0xfc, 0x9d, 0x85, 0x46, 0x7a, 0xe0, 0xcf, 0xd9, 0x58, 0x16, 0xbe,
	0x34, 0x75, 0x36, 0x58, 0x0e, 0x56, 0x0b, 0x11, 0x2d, 0xfe, 0x11, 0x9b, 0x14, 0xa0, 0xf5, 0xae,
	0x54, 0xd9, 0x70, 0x39, 0x58, 0xcd, 0xc4, 0x18, 0xcd, 0x6b, 0x85, 0xc0, 0x2f, 0xa6, 0x06, 0x04,
	0x92, 0x00, 0xa0, 0x79, 0xad, 0xf8, 0xc7, 0x6c, 0x5a, 0xd8, 0x76, 0xd7, 0x3a, 0x50, 0x59, 0xba,
	0x1c, 0xac, 0x12, 0x31, 0x29, 0x6c, 0xfb, 0xad, 0x03, 0x82, 0x2a, 0xa8, 0x02, 0x34, 0x0a, 0x50,
	0x05, 0x55, 0x07, 0x69, 0xe7, 0x02, 0x34, 0x0e, 0x90, 0x76, 0x8e, 0xa0, 0x4f, 0xd8, 0xcc, 0x9a,
	0xc6, 0x07, 0x6c, 0xb2, 0x4c, 0x56, 0x0b, 0x31, 0x45, 0x07, 0x82, 0xf9, 0x9f, 0x03, 0x36, 0x89,
	0x52, 0xf8, 0xa7, 0x2c, 0xad, 0xc0, 0x4b, 0x52, 0x30, 0xdf, 0x5c, 0xae, 0x49, 0xf8, 0xfa, 0x6e,
	0xff, 0x13, 0x14, 0xfe, 0x16, 0xbc, 0x14, 0x04, 0xf3, 0x57, 0x6c, 0x62, 0x82, 0x6a, 0x92, 0x34,
	0xdf, 0x7c, 0x18, 0x99, 0xa7, 0x29, 0x11, 0x1d, 0x8b, 0xbf, 0x64, 0xa9, 0xb3, 0x50, 0x90, 0xce,
	0xf9, 0x86, 0x9f, 0xb2, 0xef, 0x2d, 0x14, 0x82, 0x70, 0xfe, 0x39, 0x1b, 0x63, 0x96, 0x5b, 0x47,
	0xba, 0xe7, 0x9b, 0x67, 0x67, 0x4c, 0xc2, 0x44, 0xe4, 0xf0, 0xcf, 0x58, 0x62, 0x1b, 0x97, 0x8d,
	0x96, 0xc9, 0xd1, 0x13, 0xb6, 0xfb, 0xad, 0x51, 0x02, 0x6c, 0xe4, 0x22, 0x23, 0x7f, 0xcd, 0xe6,
	0x31, 0xc2, 0x4d, 0xe9, 0x3c, 0x7f, 0xc1, 0x46, 0xa5, 0x87, 0xca, 0x65, 0x43, 0x3a, 0x79, 0x71,
	0x7a, 0x89, 0x08, 0x60, 0xfe, 0xc7, 0xa0, 0x3f, 0x85, 0x2f, 0xe4, 0x6b, 0x36, 0xb5, 0x5a, 0xfa,
	0x1f, 0x4d, 0x53, 0x45, 0xd5, 0x47, 0x3a, 0xb6, 0x11, 0x11, 0x3d, 0x87, 0x6f, 0xd8, 0xb4, 0x90,
	0x56, 0x16, 0xa5, 0x7f, 0x8c, 0xba, 0x9f, 0x9f, 0x5d, 0x04, 0xce, 0xb4, 0x4d, 0x01, 0xa2, 0xe7,
	0x61, 0xa1, 0x1e, 0xbc, 0xb7, 0x3b, 0x2c, 0x0e, 0xd5, 0x77, 0x21, 0xa6, 0xe8, 0xd8, 0x9a, 0xc6,
	0xf3, 0x9c, 0x2d, 0x2c, 0x40, 0xb3, 0xd3, 0xb2, 0xde, 0x49, 0xa5, 0x1a, 0xaa, 0xf2, 0x4c, 0xcc,
	0xd1, 0x79, 0x23, 0xeb, 0x37, 0x4a, 0x35, 0x3d, 0xe7, 0x5d, 0xc7, 0x99, 0x1c, 0x38, 0xdf, 0x07,
	0x4e, 0x7e, 0x4d, 0xba, 0xba, 0x17, 0xf3, 0x0b, 0x36, 0x34, 0x8e, 0x2a, 0x3e, 0x13, 0x43, 0xe3,
	0xb0, 0x8f, 0x7f, 0x86, 0xa6, 0x06, 0xdd, 0xb5, 0x6b, 0xb0, 0x38, 0x67, 0xa9, 0x6c, 0x8a, 0x87,
	0xd8, 0xab, 0xf4, 0x9d, 0xef, 0xd8, 0x93, 0x33, 0x31, 0xfc, 0x29, 0x4b, 0x2a, 0xa8, 0x28, 0x5e,
	0x2a, 0xf0, 0x13, 0x3d, 0x85, 0x6d, 0x29, 0x5a, 0x2a, 0xf0, 0x93, 0xaf, 0x58, 0xfa, 0xd6, 0x68,
	0x97, 0x25, 0x94, 0xff, 0xb3, 0x22, 0x7f, 0x67, 0x74, 0x5b, 0x81, 0x20, 0x46, 0x7e, 0xcb, 0x16,
	0x27, 0x6e, 0x7c, 0x45, 0x2d, 0x2b, 0x88, 0xef, 0xa5, 0x6f, 0xfe, 0x8c, 0x8d, 0xbc, 0xf1, 0x52,
	0xc7, 0x2b, 0x82, 0x81, 0x4c, 0xea, 0xf7, 0x84, 0x9c, 0xf4, 0x9d, 0x57, 0x7d, 0xb8, 0xd0, 0x1e,
	0x78, 0xd4, 0x3e, 0x48, 0xd7, 0xc5, 0x0b, 0x06, 0xa6, 0xa0, 0xb5, 0xbe, 0xac, 0x42, 0x7b, 0x2f,
	0x44, 0xb4, 0xf8, 0x9a, 0x8d, 0x68, 0x09, 0xc4, 0x7a, 0x66, 0x7d, 0xcb, 0x61, 0x34, 0x77, 0x2f,
	0x2b, 0xab, 0xe1, 0x2b, 0x00, 0x25, 0x02, 0x2d, 0xff, 0x2b, 0x8c, 0xd6, 0x0f, 0xa6, 0x86, 0x7e,
	0xb4, 0x86, 0xff, 0x3d, 0x5a, 0xfd, 0x83, 0xf0, 0x8a, 0x51, 0xf7, 0xa0, 0x8c, 0x4d, 0x5c, 0x5b,
	0x55, 0xb2, 0x79, 0xa4, 0xc1, 0x98, 0x89, 0xce, 0xc4, 0x8e, 0xe9, 0x6a, 0x1d, 0x26, 0x61, 0x26,
	0xa6, 0xef, 0x42, 0xa1, 0x1d, 0x82, 0xba, 0x07, 0xc7, 0x01, 0xd4, 0x1d, 0xf8, 0x82, 0x8d, 0x70,
	0x11, 0x39, 0x5a, 0x08, 0x27, 0x53, 0xf0, 0x25, 0x68, 0x2d, 0x02, 0xc8, 0x5f, 0xe2, 0xa8, 0xe3,
	0x1e, 0x73, 0xd9, 0x94, 0x78, 0xef, 0x47, 0xde, 0x8d, 0xdc, 0x83, 0x16, 0x1d, 0x98, 0xff, 0x1a,
	0xa4, 0xe2, 0xd1, 0xff, 0x2b, 0xf5, 0x5f, 0xf7, 0x5f, 0x9f, 0x83, 0xf4, 0x38, 0x07, 0x4b, 0x36,
	0x57, 0xe0, 0x8a, 0xa6, 0xa4, 0x1b, 0x69, 0x3a, 0x66, 0xe2, 0xd8, 0x95, 0xdf, 0xb1, 0xcb, 0x98,
	0xed, 0x5b, 0x89, 0x8b, 0xfe, 0x1b, 0xa3, 0x00, 0xdb, 0xbb, 0x54, 0x5d, 0x7b, 0x97, 0x8a, 0xda,
	0x18, 0x07, 0x63, 0x18, 0xdb, 0x18, 0xa7, 0xe6, 0xb0, 0xba, 0x93, 0xe3, 0xd5, 0x9d, 0xff, 0x36,
	0x38, 0x8b, 0x48, 0xeb, 0x23, 0x63, 0x93, 0xb7, 0xd0, 0xb8, 0x6e, 0xd3, 0xa7, 0xa2, 0x33, 0x31,
	0x8e, 0x06, 0xa9, 0xa0, 0x8b, 0x1e, 0x2d, 0x3c, 0xd1, 0x5a, 0x25, 0x7d, 0xdf, 0x8d, 0x9d, 0x89,
	0x1d, 0x15, 0x56, 0x51, 0x4a, 0xc9, 0xcd, 0x0e, 0x45, 0x38, 0x95, 0x11, 0x97, 0xd2, 0xe6, 0x96,
	0x2d, 0xde, 0xd8, 0xf2, 0x80, 0xf1, 0x2f, 0xd8, 0xc5, 0xa1, 0x9d, 0xef, 0x1f, 0xeb, 0x82, 0x9f,
	0xad, 0xb3, 0xab, 0x7f, 0x8c, 0x89, 0x42, 0xf2, 0xf7, 0xf6, 0x63, 0xfa, 0x9b, 0xbd, 0xfe, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0x5d, 0x13, 0xf1, 0x21, 0x07, 0x00, 0x00,
}
