// Code generated by protoc-gen-go.
// source: inapi/cluster.proto
// DO NOT EDIT!

package inapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// host
type ResHostOperate struct {
	Action   uint32   `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	CellId   string   `protobuf:"bytes,2,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	ZoneId   string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CpuUsed  int64    `protobuf:"varint,4,opt,name=cpu_used,json=cpuUsed" json:"cpu_used,omitempty"`
	MemUsed  int64    `protobuf:"varint,5,opt,name=mem_used,json=memUsed" json:"mem_used,omitempty"`
	LssUsed  int64    `protobuf:"varint,6,opt,name=lss_used,json=lssUsed" json:"lss_used,omitempty"`
	PortUsed []uint32 `protobuf:"varint,7,rep,packed,name=port_used,json=portUsed" json:"port_used,omitempty"`
}

func (m *ResHostOperate) Reset()                    { *m = ResHostOperate{} }
func (m *ResHostOperate) String() string            { return proto.CompactTextString(m) }
func (*ResHostOperate) ProtoMessage()               {}
func (*ResHostOperate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ResHostOperate) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostOperate) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostOperate) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostOperate) GetCpuUsed() int64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *ResHostOperate) GetMemUsed() int64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *ResHostOperate) GetLssUsed() int64 {
	if m != nil {
		return m.LssUsed
	}
	return 0
}

func (m *ResHostOperate) GetPortUsed() []uint32 {
	if m != nil {
		return m.PortUsed
	}
	return nil
}

type ResHost struct {
	Meta    *ObjectMeta       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Operate *ResHostOperate   `protobuf:"bytes,2,opt,name=operate" json:"operate,omitempty"`
	Spec    *ResHostSpec      `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status  *ResHostStatus    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Prs     []*PbPodRepStatus `protobuf:"bytes,5,rep,name=prs" json:"prs,omitempty"`
}

func (m *ResHost) Reset()                    { *m = ResHost{} }
func (m *ResHost) String() string            { return proto.CompactTextString(m) }
func (*ResHost) ProtoMessage()               {}
func (*ResHost) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ResHost) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResHost) GetOperate() *ResHostOperate {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *ResHost) GetSpec() *ResHostSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ResHost) GetStatus() *ResHostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ResHost) GetPrs() []*PbPodRepStatus {
	if m != nil {
		return m.Prs
	}
	return nil
}

type ResHostNew struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Action               uint32   `protobuf:"varint,2,opt,name=action" json:"action,omitempty"`
	ZoneId               string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CellId               string   `protobuf:"bytes,4,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	PeerLanAddr          string   `protobuf:"bytes,5,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	SecretKey            string   `protobuf:"bytes,6,opt,name=secret_key,json=secretKey" json:"secret_key,omitempty"`
	ZoneMasters          []string `protobuf:"bytes,7,rep,name=zone_masters,json=zoneMasters" json:"zone_masters,omitempty"`
	ZoneIamServiceUrl    string   `protobuf:"bytes,8,opt,name=zone_iam_service_url,json=zoneIamServiceUrl" json:"zone_iam_service_url,omitempty"`
	ZoneInpackServiceUrl string   `protobuf:"bytes,9,opt,name=zone_inpack_service_url,json=zoneInpackServiceUrl" json:"zone_inpack_service_url,omitempty"`
}

func (m *ResHostNew) Reset()                    { *m = ResHostNew{} }
func (m *ResHostNew) String() string            { return proto.CompactTextString(m) }
func (*ResHostNew) ProtoMessage()               {}
func (*ResHostNew) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ResHostNew) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResHostNew) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostNew) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostNew) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostNew) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostNew) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ResHostNew) GetZoneMasters() []string {
	if m != nil {
		return m.ZoneMasters
	}
	return nil
}

func (m *ResHostNew) GetZoneIamServiceUrl() string {
	if m != nil {
		return m.ZoneIamServiceUrl
	}
	return ""
}

func (m *ResHostNew) GetZoneInpackServiceUrl() string {
	if m != nil {
		return m.ZoneInpackServiceUrl
	}
	return ""
}

type ResHostList struct {
	Items []*ResHost `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *ResHostList) Reset()                    { *m = ResHostList{} }
func (m *ResHostList) String() string            { return proto.CompactTextString(m) }
func (*ResHostList) ProtoMessage()               {}
func (*ResHostList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ResHostList) GetItems() []*ResHost {
	if m != nil {
		return m.Items
	}
	return nil
}

type ResHostSpec struct {
	Platform         *ResPlatform     `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Capacity         *ResHostResource `protobuf:"bytes,3,opt,name=capacity" json:"capacity,omitempty"`
	HttpPort         uint32           `protobuf:"varint,5,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
	PeerLanAddr      string           `protobuf:"bytes,6,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	PeerWanAddr      string           `protobuf:"bytes,7,opt,name=peer_wan_addr,json=peerWanAddr" json:"peer_wan_addr,omitempty"`
	ExpDockerVersion string           `protobuf:"bytes,10,opt,name=exp_docker_version,json=expDockerVersion" json:"exp_docker_version,omitempty"`
	ExpRktVersion    string           `protobuf:"bytes,11,opt,name=exp_rkt_version,json=expRktVersion" json:"exp_rkt_version,omitempty"`
}

func (m *ResHostSpec) Reset()                    { *m = ResHostSpec{} }
func (m *ResHostSpec) String() string            { return proto.CompactTextString(m) }
func (*ResHostSpec) ProtoMessage()               {}
func (*ResHostSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ResHostSpec) GetPlatform() *ResPlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ResHostSpec) GetCapacity() *ResHostResource {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *ResHostSpec) GetHttpPort() uint32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ResHostSpec) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostSpec) GetPeerWanAddr() string {
	if m != nil {
		return m.PeerWanAddr
	}
	return ""
}

func (m *ResHostSpec) GetExpDockerVersion() string {
	if m != nil {
		return m.ExpDockerVersion
	}
	return ""
}

func (m *ResHostSpec) GetExpRktVersion() string {
	if m != nil {
		return m.ExpRktVersion
	}
	return ""
}

type ResPlatform struct {
	Os     string `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Kernel string `protobuf:"bytes,2,opt,name=kernel" json:"kernel,omitempty"`
	Arch   string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
}

func (m *ResPlatform) Reset()                    { *m = ResPlatform{} }
func (m *ResPlatform) String() string            { return proto.CompactTextString(m) }
func (*ResPlatform) ProtoMessage()               {}
func (*ResPlatform) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ResPlatform) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ResPlatform) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *ResPlatform) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ResHostResource struct {
	Mem uint64 `protobuf:"varint,1,opt,name=mem" json:"mem,omitempty"`
	Cpu uint64 `protobuf:"varint,2,opt,name=cpu" json:"cpu,omitempty"`
}

func (m *ResHostResource) Reset()                    { *m = ResHostResource{} }
func (m *ResHostResource) String() string            { return proto.CompactTextString(m) }
func (*ResHostResource) ProtoMessage()               {}
func (*ResHostResource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ResHostResource) GetMem() uint64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

func (m *ResHostResource) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

type ResHostVolume struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Total uint64 `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Used  uint64 `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
}

func (m *ResHostVolume) Reset()                    { *m = ResHostVolume{} }
func (m *ResHostVolume) String() string            { return proto.CompactTextString(m) }
func (*ResHostVolume) ProtoMessage()               {}
func (*ResHostVolume) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ResHostVolume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResHostVolume) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResHostVolume) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type ResHostStatus struct {
	Phase   string             `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	Uptime  uint32             `protobuf:"varint,2,opt,name=uptime" json:"uptime,omitempty"`
	Volumes []*ResHostVolume   `protobuf:"bytes,3,rep,name=volumes" json:"volumes,omitempty"`
	Stats   *PbStatsSampleFeed `protobuf:"bytes,4,opt,name=stats" json:"stats,omitempty"`
}

func (m *ResHostStatus) Reset()                    { *m = ResHostStatus{} }
func (m *ResHostStatus) String() string            { return proto.CompactTextString(m) }
func (*ResHostStatus) ProtoMessage()               {}
func (*ResHostStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ResHostStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *ResHostStatus) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *ResHostStatus) GetVolumes() []*ResHostVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ResHostStatus) GetStats() *PbStatsSampleFeed {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ResHostBound struct {
	Masters   *ResZoneMasterList `protobuf:"bytes,2,opt,name=masters" json:"masters,omitempty"`
	ExpPods   []string           `protobuf:"bytes,5,rep,name=exp_pods,json=expPods" json:"exp_pods,omitempty"`
	ExpPsmaps []*NsPodServiceMap `protobuf:"bytes,6,rep,name=exp_psmaps,json=expPsmaps" json:"exp_psmaps,omitempty"`
}

func (m *ResHostBound) Reset()                    { *m = ResHostBound{} }
func (m *ResHostBound) String() string            { return proto.CompactTextString(m) }
func (*ResHostBound) ProtoMessage()               {}
func (*ResHostBound) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ResHostBound) GetMasters() *ResZoneMasterList {
	if m != nil {
		return m.Masters
	}
	return nil
}

func (m *ResHostBound) GetExpPods() []string {
	if m != nil {
		return m.ExpPods
	}
	return nil
}

func (m *ResHostBound) GetExpPsmaps() []*NsPodServiceMap {
	if m != nil {
		return m.ExpPsmaps
	}
	return nil
}

type ResZone struct {
	Meta     *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Phase    int32       `protobuf:"varint,3,opt,name=phase" json:"phase,omitempty"`
	Summary  string      `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	WanAddrs []string    `protobuf:"bytes,5,rep,name=wan_addrs,json=wanAddrs" json:"wan_addrs,omitempty"`
	LanAddrs []string    `protobuf:"bytes,6,rep,name=lan_addrs,json=lanAddrs" json:"lan_addrs,omitempty"`
	Cells    []*ResCell  `protobuf:"bytes,7,rep,name=cells" json:"cells,omitempty"`
	Options  []*Label    `protobuf:"bytes,8,rep,name=options" json:"options,omitempty"`
}

func (m *ResZone) Reset()                    { *m = ResZone{} }
func (m *ResZone) String() string            { return proto.CompactTextString(m) }
func (*ResZone) ProtoMessage()               {}
func (*ResZone) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ResZone) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResZone) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResZone) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ResZone) GetWanAddrs() []string {
	if m != nil {
		return m.WanAddrs
	}
	return nil
}

func (m *ResZone) GetLanAddrs() []string {
	if m != nil {
		return m.LanAddrs
	}
	return nil
}

func (m *ResZone) GetCells() []*ResCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *ResZone) GetOptions() []*Label {
	if m != nil {
		return m.Options
	}
	return nil
}

type ResCell struct {
	Meta        *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	ZoneId      string      `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Phase       int32       `protobuf:"varint,4,opt,name=phase" json:"phase,omitempty"`
	Description string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	NodeNum     int32       `protobuf:"varint,6,opt,name=node_num,json=nodeNum" json:"node_num,omitempty"`
}

func (m *ResCell) Reset()                    { *m = ResCell{} }
func (m *ResCell) String() string            { return proto.CompactTextString(m) }
func (*ResCell) ProtoMessage()               {}
func (*ResCell) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ResCell) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResCell) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResCell) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResCell) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResCell) GetNodeNum() int32 {
	if m != nil {
		return m.NodeNum
	}
	return 0
}

type ResZoneMasterNode struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addr   string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Action uint32 `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
}

func (m *ResZoneMasterNode) Reset()                    { *m = ResZoneMasterNode{} }
func (m *ResZoneMasterNode) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterNode) ProtoMessage()               {}
func (*ResZoneMasterNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *ResZoneMasterNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResZoneMasterNode) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ResZoneMasterNode) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ResZoneMasterList struct {
	Version uint64               `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Leader  string               `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	Updated uint64               `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Items   []*ResZoneMasterNode `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *ResZoneMasterList) Reset()                    { *m = ResZoneMasterList{} }
func (m *ResZoneMasterList) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterList) ProtoMessage()               {}
func (*ResZoneMasterList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *ResZoneMasterList) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResZoneMasterList) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *ResZoneMasterList) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ResZoneMasterList) GetItems() []*ResZoneMasterNode {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ResHostOperate)(nil), "inapi.ResHostOperate")
	proto.RegisterType((*ResHost)(nil), "inapi.ResHost")
	proto.RegisterType((*ResHostNew)(nil), "inapi.ResHostNew")
	proto.RegisterType((*ResHostList)(nil), "inapi.ResHostList")
	proto.RegisterType((*ResHostSpec)(nil), "inapi.ResHostSpec")
	proto.RegisterType((*ResPlatform)(nil), "inapi.ResPlatform")
	proto.RegisterType((*ResHostResource)(nil), "inapi.ResHostResource")
	proto.RegisterType((*ResHostVolume)(nil), "inapi.ResHostVolume")
	proto.RegisterType((*ResHostStatus)(nil), "inapi.ResHostStatus")
	proto.RegisterType((*ResHostBound)(nil), "inapi.ResHostBound")
	proto.RegisterType((*ResZone)(nil), "inapi.ResZone")
	proto.RegisterType((*ResCell)(nil), "inapi.ResCell")
	proto.RegisterType((*ResZoneMasterNode)(nil), "inapi.ResZoneMasterNode")
	proto.RegisterType((*ResZoneMasterList)(nil), "inapi.ResZoneMasterList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiHostMember service

type ApiHostMemberClient interface {
	HostJoin(ctx context.Context, in *ResHostNew, opts ...grpc.CallOption) (*ResHost, error)
}

type apiHostMemberClient struct {
	cc *grpc.ClientConn
}

func NewApiHostMemberClient(cc *grpc.ClientConn) ApiHostMemberClient {
	return &apiHostMemberClient{cc}
}

func (c *apiHostMemberClient) HostJoin(ctx context.Context, in *ResHostNew, opts ...grpc.CallOption) (*ResHost, error) {
	out := new(ResHost)
	err := grpc.Invoke(ctx, "/inapi.ApiHostMember/HostJoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiHostMember service

type ApiHostMemberServer interface {
	HostJoin(context.Context, *ResHostNew) (*ResHost, error)
}

func RegisterApiHostMemberServer(s *grpc.Server, srv ApiHostMemberServer) {
	s.RegisterService(&_ApiHostMember_serviceDesc, srv)
}

func _ApiHostMember_HostJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHostNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiHostMemberServer).HostJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inapi.ApiHostMember/HostJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiHostMemberServer).HostJoin(ctx, req.(*ResHostNew))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiHostMember_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ApiHostMember",
	HandlerType: (*ApiHostMemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostJoin",
			Handler:    _ApiHostMember_HostJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inapi/cluster.proto",
}

// Client API for ApiZoneMaster service

type ApiZoneMasterClient interface {
	HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResHostBound, error)
}

type apiZoneMasterClient struct {
	cc *grpc.ClientConn
}

func NewApiZoneMasterClient(cc *grpc.ClientConn) ApiZoneMasterClient {
	return &apiZoneMasterClient{cc}
}

func (c *apiZoneMasterClient) HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResHostBound, error) {
	out := new(ResHostBound)
	err := grpc.Invoke(ctx, "/inapi.ApiZoneMaster/HostStatusSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiZoneMaster service

type ApiZoneMasterServer interface {
	HostStatusSync(context.Context, *ResHost) (*ResHostBound, error)
}

func RegisterApiZoneMasterServer(s *grpc.Server, srv ApiZoneMasterServer) {
	s.RegisterService(&_ApiZoneMaster_serviceDesc, srv)
}

func _ApiZoneMaster_HostStatusSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inapi.ApiZoneMaster/HostStatusSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, req.(*ResHost))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiZoneMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ApiZoneMaster",
	HandlerType: (*ApiZoneMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostStatusSync",
			Handler:    _ApiZoneMaster_HostStatusSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inapi/cluster.proto",
}

func init() { proto.RegisterFile("inapi/cluster.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x6e, 0x7e, 0x9d, 0x4c, 0x9a, 0x6d, 0x77, 0x5a, 0x5a, 0xb3, 0x08, 0x69, 0xb1, 0x4a, 0xd9,
	0x8b, 0x92, 0x95, 0x52, 0x55, 0xdc, 0x52, 0x40, 0xa8, 0x0b, 0xdd, 0x6d, 0x34, 0xab, 0x16, 0x89,
	0x9b, 0x68, 0x62, 0x1f, 0x54, 0x13, 0xdb, 0x33, 0xf2, 0x8c, 0xbb, 0xbb, 0xbc, 0x04, 0x37, 0x5c,
	0xc2, 0x1b, 0xf0, 0x00, 0x3c, 0x02, 0x8f, 0xc1, 0x25, 0x8f, 0x81, 0xce, 0x99, 0x19, 0x6f, 0x92,
	0x16, 0xc4, 0x9d, 0xcf, 0xf9, 0xbe, 0x73, 0xec, 0xf3, 0xf7, 0x25, 0xec, 0x4e, 0x5e, 0x49, 0x9d,
	0x1f, 0xa7, 0x45, 0x63, 0x2c, 0xd4, 0x33, 0x5d, 0x2b, 0xab, 0xf8, 0x80, 0x9c, 0x07, 0xb7, 0x1d,
	0xb6, 0x92, 0x06, 0x1c, 0x70, 0x70, 0xcb, 0x79, 0xb4, 0xca, 0xbc, 0x63, 0xdf, 0x39, 0x8c, 0x95,
	0xd6, 0x78, 0xd7, 0x3d, 0xe7, 0xaa, 0xcc, 0xa7, 0x06, 0xea, 0x37, 0x79, 0xea, 0x63, 0x93, 0x3f,
	0x3b, 0x6c, 0x4f, 0x80, 0x79, 0xa6, 0x8c, 0x7d, 0xa1, 0xa1, 0x96, 0x16, 0xf8, 0x3d, 0x36, 0x94,
	0xa9, 0xcd, 0x55, 0x15, 0x77, 0x0e, 0x3b, 0x47, 0x53, 0xe1, 0x2d, 0x7e, 0x9f, 0x45, 0x29, 0x14,
	0xc5, 0x32, 0xcf, 0xe2, 0xee, 0x61, 0xe7, 0x68, 0x2c, 0x86, 0x68, 0x9e, 0x64, 0x08, 0xfc, 0xa4,
	0x2a, 0x40, 0xa0, 0xe7, 0x00, 0x34, 0x4f, 0x32, 0xfe, 0x3e, 0x1b, 0xa5, 0xba, 0x59, 0x36, 0x06,
	0xb2, 0xb8, 0x7f, 0xd8, 0x39, 0xea, 0x89, 0x28, 0xd5, 0xcd, 0x4b, 0x03, 0x04, 0x95, 0x50, 0x3a,
	0x68, 0xe0, 0xa0, 0x12, 0xca, 0x00, 0x15, 0xc6, 0x38, 0x68, 0xe8, 0xa0, 0xc2, 0x18, 0x82, 0x3e,
	0x60, 0x63, 0xad, 0x6a, 0xeb, 0xb0, 0xe8, 0xb0, 0x77, 0x34, 0x15, 0x23, 0x74, 0x20, 0x98, 0xfc,
	0xd5, 0x61, 0x91, 0x2f, 0x85, 0x7f, 0xcc, 0xfa, 0x25, 0x58, 0x49, 0x15, 0x4c, 0xe6, 0xfb, 0x33,
	0xaa, 0x7e, 0xf6, 0x62, 0xf5, 0x23, 0xa4, 0xf6, 0x14, 0xac, 0x14, 0x04, 0xf3, 0x63, 0x16, 0x29,
	0x57, 0x35, 0x95, 0x34, 0x99, 0xbf, 0xe7, 0x99, 0xdb, 0x2d, 0x11, 0x81, 0xc5, 0x1f, 0xb2, 0xbe,
	0xd1, 0x90, 0x52, 0x9d, 0x93, 0x39, 0xdf, 0x66, 0x9f, 0x6b, 0x48, 0x05, 0xe1, 0xfc, 0x11, 0x1b,
	0x62, 0xf7, 0x1b, 0x43, 0x75, 0x4f, 0xe6, 0x77, 0x77, 0x98, 0x84, 0x09, 0xcf, 0xe1, 0x9f, 0xb0,
	0x9e, 0xae, 0x4d, 0x3c, 0x38, 0xec, 0x6d, 0x7c, 0xc2, 0x62, 0xb5, 0x50, 0x99, 0x00, 0xed, 0xb9,
	0xc8, 0x48, 0xfe, 0xe8, 0x32, 0xe6, 0x53, 0x9c, 0xc1, 0x05, 0xe7, 0xac, 0x5f, 0xc9, 0x12, 0xa8,
	0xca, 0xb1, 0xa0, 0xe7, 0x8d, 0xe9, 0x75, 0x77, 0xa7, 0xf7, 0xee, 0x21, 0x6d, 0x8c, 0xb5, 0xbf,
	0x35, 0xd6, 0x84, 0x4d, 0x35, 0x40, 0xbd, 0x2c, 0x64, 0xb5, 0x94, 0x59, 0x56, 0xd3, 0x9c, 0xc6,
	0x62, 0x82, 0xce, 0xe7, 0xb2, 0x7a, 0x9a, 0x65, 0x35, 0xff, 0x90, 0x31, 0x03, 0x69, 0x0d, 0x76,
	0xb9, 0x86, 0x2b, 0x9a, 0xd6, 0x58, 0x8c, 0x9d, 0xe7, 0x5b, 0xb8, 0xe2, 0x1f, 0xb1, 0x9b, 0xf4,
	0xd2, 0x52, 0xe2, 0x1e, 0x1b, 0x1a, 0xd9, 0x58, 0x4c, 0xd0, 0x77, 0xea, 0x5c, 0xfc, 0x98, 0xdd,
	0x75, 0xdf, 0x25, 0xcb, 0xa5, 0x5f, 0xcd, 0x65, 0x53, 0x17, 0xf1, 0x88, 0x72, 0xed, 0xd3, 0x47,
	0xca, 0xf2, 0xdc, 0x21, 0x2f, 0xeb, 0x82, 0x3f, 0x61, 0xf7, 0x5d, 0x40, 0xa5, 0x65, 0xba, 0xde,
	0x8a, 0x19, 0x53, 0x0c, 0xe5, 0x3b, 0x21, 0xf4, 0x3a, 0x2c, 0x79, 0xcc, 0x26, 0xbe, 0x73, 0xcf,
	0x73, 0x63, 0xf9, 0x03, 0x36, 0xc8, 0x2d, 0x94, 0x26, 0xee, 0x52, 0xd3, 0xf7, 0xb6, 0xe7, 0x23,
	0x1c, 0x98, 0xfc, 0xde, 0x6d, 0xa3, 0x70, 0xb8, 0x7c, 0xc6, 0x46, 0xba, 0x90, 0xf6, 0x07, 0x55,
	0x97, 0x7e, 0x61, 0x36, 0x56, 0x60, 0xe1, 0x11, 0xd1, 0x72, 0xf8, 0x9c, 0x8d, 0x52, 0xa9, 0x65,
	0x9a, 0xdb, 0x2b, 0xbf, 0x32, 0xf7, 0x76, 0x5e, 0x04, 0x46, 0x35, 0x75, 0x0a, 0xa2, 0xe5, 0xe1,
	0x8e, 0xbf, 0xb6, 0x56, 0x2f, 0x71, 0xaf, 0xa9, 0xe5, 0x53, 0x31, 0x42, 0xc7, 0x42, 0xd5, 0xf6,
	0xed, 0x99, 0x0c, 0xdf, 0x9e, 0x49, 0xe0, 0x5c, 0x04, 0x4e, 0x74, 0xcd, 0xf9, 0xce, 0x73, 0x1e,
	0x31, 0x0e, 0x97, 0x7a, 0x99, 0xa9, 0x74, 0x0d, 0xf5, 0xf2, 0x0d, 0xd4, 0x06, 0x37, 0x86, 0x11,
	0xf1, 0x36, 0x5c, 0xea, 0xaf, 0x08, 0x78, 0xe5, 0xfc, 0xfc, 0x21, 0xbb, 0x85, 0xec, 0x7a, 0x6d,
	0x5b, 0xea, 0x84, 0xa8, 0x53, 0xb8, 0xd4, 0x62, 0x6d, 0x3d, 0x2f, 0x39, 0xa1, 0x6e, 0x85, 0x3e,
	0xf0, 0x3d, 0xd6, 0x55, 0xc6, 0x2f, 0x67, 0x57, 0x19, 0x5c, 0xcd, 0x35, 0xd4, 0x15, 0x14, 0x41,
	0x3f, 0x9c, 0x85, 0x6b, 0x2c, 0xeb, 0xf4, 0xb5, 0xdf, 0x4b, 0x7a, 0x4e, 0x9e, 0xb0, 0x5b, 0x3b,
	0x2d, 0xe2, 0xb7, 0x59, 0xaf, 0x84, 0x92, 0xf2, 0xf5, 0x05, 0x3e, 0xa2, 0x27, 0xd5, 0x0d, 0x65,
	0xeb, 0x0b, 0x7c, 0x4c, 0x4e, 0xd9, 0xd4, 0x87, 0xbd, 0x52, 0x45, 0x53, 0xc2, 0x3b, 0x4f, 0xe4,
	0x2e, 0x1b, 0x58, 0x65, 0x65, 0xe1, 0x03, 0x9d, 0x81, 0x4c, 0x92, 0x95, 0x1e, 0x39, 0xe9, 0x39,
	0xf9, 0xad, 0xd3, 0xe6, 0x73, 0x67, 0x88, 0xb1, 0xfa, 0xb5, 0x34, 0x21, 0xa1, 0x33, 0xb0, 0xb2,
	0x46, 0xdb, 0xbc, 0x84, 0x70, 0x74, 0xce, 0xe2, 0x33, 0x16, 0xbd, 0xa1, 0xef, 0x30, 0x71, 0x8f,
	0xf6, 0x6c, 0x47, 0x07, 0xdc, 0x47, 0x8a, 0x40, 0xe2, 0x33, 0x36, 0x20, 0xd1, 0xf6, 0xaa, 0x11,
	0xb7, 0x52, 0x80, 0x6f, 0x37, 0xe7, 0xb2, 0xd4, 0x05, 0x7c, 0x0d, 0x90, 0x09, 0x47, 0x4b, 0x7e,
	0xe9, 0xb0, 0x9b, 0x3e, 0xd5, 0x17, 0xaa, 0xa9, 0x32, 0x3e, 0x67, 0x51, 0xb8, 0xb5, 0xee, 0x56,
	0x0a, 0x01, 0xe6, 0xfb, 0xf6, 0xea, 0xf0, 0x02, 0x44, 0x20, 0xa2, 0xde, 0xe2, 0x74, 0xb5, 0xca,
	0x9c, 0x04, 0x8d, 0x45, 0x04, 0x97, 0x7a, 0xa1, 0x32, 0xc3, 0x9f, 0x30, 0x46, 0x90, 0x29, 0xa5,
	0x36, 0xf1, 0x90, 0x4a, 0x08, 0x1b, 0x7c, 0x66, 0x16, 0x2a, 0xf3, 0x07, 0x76, 0x2a, 0xb5, 0x18,
	0x63, 0x10, 0x11, 0x93, 0xbf, 0x9d, 0x12, 0xe3, 0x0b, 0x5b, 0x25, 0xee, 0xfe, 0xb7, 0x12, 0xb7,
	0x7d, 0xc5, 0xf6, 0x0f, 0x42, 0x5f, 0x63, 0x16, 0x99, 0xa6, 0x2c, 0x65, 0x7d, 0xe5, 0xb5, 0x29,
	0x98, 0x78, 0x25, 0x61, 0xbf, 0xc3, 0x57, 0x8f, 0x2e, 0xdc, 0x72, 0x1b, 0x04, 0x8b, 0x16, 0x1c,
	0x3a, 0xb0, 0x08, 0xe0, 0x03, 0x36, 0x40, 0x81, 0x73, 0x62, 0xb4, 0x75, 0xf9, 0x5f, 0x42, 0x51,
	0x08, 0x07, 0xf2, 0x87, 0xf8, 0xcb, 0x80, 0xc2, 0x69, 0xe2, 0x11, 0xf1, 0x6e, 0x7a, 0xde, 0x73,
	0xb9, 0x82, 0x42, 0x04, 0x30, 0xf9, 0xd5, 0x95, 0x8a, 0xa1, 0xff, 0xb7, 0xd4, 0x7f, 0x55, 0xe2,
	0xb6, 0x07, 0xfd, 0xcd, 0x1e, 0x1c, 0xb2, 0x49, 0x06, 0x26, 0xad, 0x73, 0x7a, 0x63, 0x10, 0xe1,
	0x0d, 0x17, 0x0e, 0xb0, 0x52, 0x19, 0x2c, 0xab, 0xa6, 0x24, 0x3d, 0x18, 0x88, 0x08, 0xed, 0xb3,
	0xa6, 0x4c, 0x5e, 0xb0, 0xfd, 0xad, 0xc9, 0x9f, 0xa9, 0x0c, 0xf0, 0x2e, 0xf3, 0x2c, 0xdc, 0x65,
	0x9e, 0xd1, 0xfd, 0xa1, 0x4e, 0x74, 0xfd, 0xfd, 0xa1, 0x40, 0x5c, 0xff, 0x8c, 0xf4, 0x36, 0x7f,
	0x46, 0x92, 0x9f, 0x3b, 0x3b, 0x19, 0x49, 0x4d, 0x63, 0x16, 0x05, 0x61, 0x70, 0xe7, 0x19, 0x4c,
	0xcc, 0x53, 0x80, 0xcc, 0x20, 0x64, 0xf7, 0x16, 0x46, 0x34, 0x3a, 0x93, 0xb6, 0x3d, 0xb8, 0x60,
	0xe2, 0x0d, 0x38, 0x65, 0xee, 0x53, 0xdf, 0xdf, 0xb9, 0xc0, 0x58, 0x86, 0xd7, 0xe8, 0xf9, 0xe7,
	0x6c, 0xfa, 0x54, 0xe7, 0x78, 0x02, 0xa7, 0x50, 0xae, 0xa0, 0xe6, 0xc7, 0x6c, 0x84, 0xd6, 0x37,
	0x2a, 0xaf, 0xf8, 0xfe, 0xf6, 0xbd, 0x9d, 0xc1, 0xc5, 0xc1, 0x8e, 0xd4, 0x27, 0x37, 0xe6, 0xcf,
	0x28, 0xc3, 0x75, 0x76, 0xfe, 0x19, 0xdb, 0xbb, 0x3e, 0xf9, 0xf3, 0xab, 0x2a, 0xe5, 0x3b, 0x41,
	0x07, 0x77, 0xb6, 0x6d, 0x3a, 0xbe, 0xe4, 0xc6, 0x6a, 0x48, 0x7f, 0xaa, 0x1e, 0xff, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x68, 0xec, 0x9f, 0xc0, 0x09, 0x00, 0x00,
}
