// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inapi/cluster.proto

package inapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// host
type ResHostOperate struct {
	Action               uint32   `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	CellId               string   `protobuf:"bytes,2,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	ZoneId               string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CpuUsed              int32    `protobuf:"varint,4,opt,name=cpu_used,json=cpuUsed" json:"cpu_used,omitempty"`
	MemUsed              int64    `protobuf:"varint,5,opt,name=mem_used,json=memUsed" json:"mem_used,omitempty"`
	LssUsed              int64    `protobuf:"varint,6,opt,name=lss_used,json=lssUsed" json:"lss_used,omitempty"`
	PortUsed             []uint32 `protobuf:"varint,7,rep,packed,name=port_used,json=portUsed" json:"port_used,omitempty"`
	BoxNum               int32    `protobuf:"varint,8,opt,name=box_num,json=boxNum" json:"box_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHostOperate) Reset()         { *m = ResHostOperate{} }
func (m *ResHostOperate) String() string { return proto.CompactTextString(m) }
func (*ResHostOperate) ProtoMessage()    {}
func (*ResHostOperate) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{0}
}
func (m *ResHostOperate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostOperate.Unmarshal(m, b)
}
func (m *ResHostOperate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostOperate.Marshal(b, m, deterministic)
}
func (dst *ResHostOperate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostOperate.Merge(dst, src)
}
func (m *ResHostOperate) XXX_Size() int {
	return xxx_messageInfo_ResHostOperate.Size(m)
}
func (m *ResHostOperate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostOperate.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostOperate proto.InternalMessageInfo

func (m *ResHostOperate) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostOperate) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostOperate) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostOperate) GetCpuUsed() int32 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *ResHostOperate) GetMemUsed() int64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *ResHostOperate) GetLssUsed() int64 {
	if m != nil {
		return m.LssUsed
	}
	return 0
}

func (m *ResHostOperate) GetPortUsed() []uint32 {
	if m != nil {
		return m.PortUsed
	}
	return nil
}

func (m *ResHostOperate) GetBoxNum() int32 {
	if m != nil {
		return m.BoxNum
	}
	return 0
}

type ResHost struct {
	Meta                 *ObjectMeta       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Operate              *ResHostOperate   `protobuf:"bytes,2,opt,name=operate" json:"operate,omitempty"`
	Spec                 *ResHostSpec      `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status               *ResHostStatus    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Prs                  []*PbPodRepStatus `protobuf:"bytes,5,rep,name=prs" json:"prs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResHost) Reset()         { *m = ResHost{} }
func (m *ResHost) String() string { return proto.CompactTextString(m) }
func (*ResHost) ProtoMessage()    {}
func (*ResHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{1}
}
func (m *ResHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHost.Unmarshal(m, b)
}
func (m *ResHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHost.Marshal(b, m, deterministic)
}
func (dst *ResHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHost.Merge(dst, src)
}
func (m *ResHost) XXX_Size() int {
	return xxx_messageInfo_ResHost.Size(m)
}
func (m *ResHost) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHost.DiscardUnknown(m)
}

var xxx_messageInfo_ResHost proto.InternalMessageInfo

func (m *ResHost) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResHost) GetOperate() *ResHostOperate {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *ResHost) GetSpec() *ResHostSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ResHost) GetStatus() *ResHostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ResHost) GetPrs() []*PbPodRepStatus {
	if m != nil {
		return m.Prs
	}
	return nil
}

type ResHostNew struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Action               uint32   `protobuf:"varint,2,opt,name=action" json:"action,omitempty"`
	ZoneId               string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CellId               string   `protobuf:"bytes,4,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	PeerLanAddr          string   `protobuf:"bytes,5,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	SecretKey            string   `protobuf:"bytes,6,opt,name=secret_key,json=secretKey" json:"secret_key,omitempty"`
	ZoneMasters          []string `protobuf:"bytes,7,rep,name=zone_masters,json=zoneMasters" json:"zone_masters,omitempty"`
	ZoneIamServiceUrl    string   `protobuf:"bytes,8,opt,name=zone_iam_service_url,json=zoneIamServiceUrl" json:"zone_iam_service_url,omitempty"`
	ZoneInpackServiceUrl string   `protobuf:"bytes,9,opt,name=zone_inpack_service_url,json=zoneInpackServiceUrl" json:"zone_inpack_service_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHostNew) Reset()         { *m = ResHostNew{} }
func (m *ResHostNew) String() string { return proto.CompactTextString(m) }
func (*ResHostNew) ProtoMessage()    {}
func (*ResHostNew) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{2}
}
func (m *ResHostNew) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostNew.Unmarshal(m, b)
}
func (m *ResHostNew) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostNew.Marshal(b, m, deterministic)
}
func (dst *ResHostNew) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostNew.Merge(dst, src)
}
func (m *ResHostNew) XXX_Size() int {
	return xxx_messageInfo_ResHostNew.Size(m)
}
func (m *ResHostNew) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostNew.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostNew proto.InternalMessageInfo

func (m *ResHostNew) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResHostNew) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostNew) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostNew) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostNew) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostNew) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ResHostNew) GetZoneMasters() []string {
	if m != nil {
		return m.ZoneMasters
	}
	return nil
}

func (m *ResHostNew) GetZoneIamServiceUrl() string {
	if m != nil {
		return m.ZoneIamServiceUrl
	}
	return ""
}

func (m *ResHostNew) GetZoneInpackServiceUrl() string {
	if m != nil {
		return m.ZoneInpackServiceUrl
	}
	return ""
}

type ResHostList struct {
	Items                []*ResHost `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResHostList) Reset()         { *m = ResHostList{} }
func (m *ResHostList) String() string { return proto.CompactTextString(m) }
func (*ResHostList) ProtoMessage()    {}
func (*ResHostList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{3}
}
func (m *ResHostList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostList.Unmarshal(m, b)
}
func (m *ResHostList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostList.Marshal(b, m, deterministic)
}
func (dst *ResHostList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostList.Merge(dst, src)
}
func (m *ResHostList) XXX_Size() int {
	return xxx_messageInfo_ResHostList.Size(m)
}
func (m *ResHostList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostList.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostList proto.InternalMessageInfo

func (m *ResHostList) GetItems() []*ResHost {
	if m != nil {
		return m.Items
	}
	return nil
}

type ResHostSpec struct {
	Platform             *ResPlatform     `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Capacity             *ResHostResource `protobuf:"bytes,3,opt,name=capacity" json:"capacity,omitempty"`
	HttpPort             uint32           `protobuf:"varint,5,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
	PeerLanAddr          string           `protobuf:"bytes,6,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	PeerWanAddr          string           `protobuf:"bytes,7,opt,name=peer_wan_addr,json=peerWanAddr" json:"peer_wan_addr,omitempty"`
	ExpDockerVersion     string           `protobuf:"bytes,10,opt,name=exp_docker_version,json=expDockerVersion" json:"exp_docker_version,omitempty"`
	ExpRktVersion        string           `protobuf:"bytes,11,opt,name=exp_rkt_version,json=expRktVersion" json:"exp_rkt_version,omitempty"`
	ExpPouchVersion      string           `protobuf:"bytes,12,opt,name=exp_pouch_version,json=expPouchVersion" json:"exp_pouch_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResHostSpec) Reset()         { *m = ResHostSpec{} }
func (m *ResHostSpec) String() string { return proto.CompactTextString(m) }
func (*ResHostSpec) ProtoMessage()    {}
func (*ResHostSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{4}
}
func (m *ResHostSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostSpec.Unmarshal(m, b)
}
func (m *ResHostSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostSpec.Marshal(b, m, deterministic)
}
func (dst *ResHostSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostSpec.Merge(dst, src)
}
func (m *ResHostSpec) XXX_Size() int {
	return xxx_messageInfo_ResHostSpec.Size(m)
}
func (m *ResHostSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostSpec proto.InternalMessageInfo

func (m *ResHostSpec) GetPlatform() *ResPlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ResHostSpec) GetCapacity() *ResHostResource {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *ResHostSpec) GetHttpPort() uint32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ResHostSpec) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostSpec) GetPeerWanAddr() string {
	if m != nil {
		return m.PeerWanAddr
	}
	return ""
}

func (m *ResHostSpec) GetExpDockerVersion() string {
	if m != nil {
		return m.ExpDockerVersion
	}
	return ""
}

func (m *ResHostSpec) GetExpRktVersion() string {
	if m != nil {
		return m.ExpRktVersion
	}
	return ""
}

func (m *ResHostSpec) GetExpPouchVersion() string {
	if m != nil {
		return m.ExpPouchVersion
	}
	return ""
}

type ResPlatform struct {
	Os                   string   `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Kernel               string   `protobuf:"bytes,2,opt,name=kernel" json:"kernel,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResPlatform) Reset()         { *m = ResPlatform{} }
func (m *ResPlatform) String() string { return proto.CompactTextString(m) }
func (*ResPlatform) ProtoMessage()    {}
func (*ResPlatform) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{5}
}
func (m *ResPlatform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResPlatform.Unmarshal(m, b)
}
func (m *ResPlatform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResPlatform.Marshal(b, m, deterministic)
}
func (dst *ResPlatform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResPlatform.Merge(dst, src)
}
func (m *ResPlatform) XXX_Size() int {
	return xxx_messageInfo_ResPlatform.Size(m)
}
func (m *ResPlatform) XXX_DiscardUnknown() {
	xxx_messageInfo_ResPlatform.DiscardUnknown(m)
}

var xxx_messageInfo_ResPlatform proto.InternalMessageInfo

func (m *ResPlatform) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ResPlatform) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *ResPlatform) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ResHostResource struct {
	Mem                  int64    `protobuf:"varint,1,opt,name=mem" json:"mem,omitempty"`
	Cpu                  int32    `protobuf:"varint,2,opt,name=cpu" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHostResource) Reset()         { *m = ResHostResource{} }
func (m *ResHostResource) String() string { return proto.CompactTextString(m) }
func (*ResHostResource) ProtoMessage()    {}
func (*ResHostResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{6}
}
func (m *ResHostResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostResource.Unmarshal(m, b)
}
func (m *ResHostResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostResource.Marshal(b, m, deterministic)
}
func (dst *ResHostResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostResource.Merge(dst, src)
}
func (m *ResHostResource) XXX_Size() int {
	return xxx_messageInfo_ResHostResource.Size(m)
}
func (m *ResHostResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostResource.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostResource proto.InternalMessageInfo

func (m *ResHostResource) GetMem() int64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

func (m *ResHostResource) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

type ResHostVolume struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Total                uint64   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Used                 uint64   `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHostVolume) Reset()         { *m = ResHostVolume{} }
func (m *ResHostVolume) String() string { return proto.CompactTextString(m) }
func (*ResHostVolume) ProtoMessage()    {}
func (*ResHostVolume) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{7}
}
func (m *ResHostVolume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostVolume.Unmarshal(m, b)
}
func (m *ResHostVolume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostVolume.Marshal(b, m, deterministic)
}
func (dst *ResHostVolume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostVolume.Merge(dst, src)
}
func (m *ResHostVolume) XXX_Size() int {
	return xxx_messageInfo_ResHostVolume.Size(m)
}
func (m *ResHostVolume) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostVolume.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostVolume proto.InternalMessageInfo

func (m *ResHostVolume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResHostVolume) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResHostVolume) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type ResHostStatus struct {
	Phase                string             `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	Uptime               uint32             `protobuf:"varint,2,opt,name=uptime" json:"uptime,omitempty"`
	Volumes              []*ResHostVolume   `protobuf:"bytes,3,rep,name=volumes" json:"volumes,omitempty"`
	Stats                *PbStatsSampleFeed `protobuf:"bytes,4,opt,name=stats" json:"stats,omitempty"`
	Updated              uint32             `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResHostStatus) Reset()         { *m = ResHostStatus{} }
func (m *ResHostStatus) String() string { return proto.CompactTextString(m) }
func (*ResHostStatus) ProtoMessage()    {}
func (*ResHostStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{8}
}
func (m *ResHostStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostStatus.Unmarshal(m, b)
}
func (m *ResHostStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostStatus.Marshal(b, m, deterministic)
}
func (dst *ResHostStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostStatus.Merge(dst, src)
}
func (m *ResHostStatus) XXX_Size() int {
	return xxx_messageInfo_ResHostStatus.Size(m)
}
func (m *ResHostStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostStatus proto.InternalMessageInfo

func (m *ResHostStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *ResHostStatus) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *ResHostStatus) GetVolumes() []*ResHostVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ResHostStatus) GetStats() *PbStatsSampleFeed {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *ResHostStatus) GetUpdated() uint32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ResHostBound struct {
	Masters              *ResZoneMasterList `protobuf:"bytes,2,opt,name=masters" json:"masters,omitempty"`
	ExpPods              []string           `protobuf:"bytes,5,rep,name=exp_pods,json=expPods" json:"exp_pods,omitempty"`
	ZoneInpackServiceUrl string             `protobuf:"bytes,7,opt,name=zone_inpack_service_url,json=zoneInpackServiceUrl" json:"zone_inpack_service_url,omitempty"`
	ExpBoxRemoves        []string           `protobuf:"bytes,8,rep,name=exp_box_removes,json=expBoxRemoves" json:"exp_box_removes,omitempty"`
	ExpBoxStops          []string           `protobuf:"bytes,9,rep,name=exp_box_stops,json=expBoxStops" json:"exp_box_stops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResHostBound) Reset()         { *m = ResHostBound{} }
func (m *ResHostBound) String() string { return proto.CompactTextString(m) }
func (*ResHostBound) ProtoMessage()    {}
func (*ResHostBound) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{9}
}
func (m *ResHostBound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHostBound.Unmarshal(m, b)
}
func (m *ResHostBound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHostBound.Marshal(b, m, deterministic)
}
func (dst *ResHostBound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHostBound.Merge(dst, src)
}
func (m *ResHostBound) XXX_Size() int {
	return xxx_messageInfo_ResHostBound.Size(m)
}
func (m *ResHostBound) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHostBound.DiscardUnknown(m)
}

var xxx_messageInfo_ResHostBound proto.InternalMessageInfo

func (m *ResHostBound) GetMasters() *ResZoneMasterList {
	if m != nil {
		return m.Masters
	}
	return nil
}

func (m *ResHostBound) GetExpPods() []string {
	if m != nil {
		return m.ExpPods
	}
	return nil
}

func (m *ResHostBound) GetZoneInpackServiceUrl() string {
	if m != nil {
		return m.ZoneInpackServiceUrl
	}
	return ""
}

func (m *ResHostBound) GetExpBoxRemoves() []string {
	if m != nil {
		return m.ExpBoxRemoves
	}
	return nil
}

func (m *ResHostBound) GetExpBoxStops() []string {
	if m != nil {
		return m.ExpBoxStops
	}
	return nil
}

type ResZone struct {
	Meta                 *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Phase                int32       `protobuf:"varint,3,opt,name=phase" json:"phase,omitempty"`
	Summary              string      `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	WanAddrs             []string    `protobuf:"bytes,5,rep,name=wan_addrs,json=wanAddrs" json:"wan_addrs,omitempty"`
	LanAddrs             []string    `protobuf:"bytes,6,rep,name=lan_addrs,json=lanAddrs" json:"lan_addrs,omitempty"`
	Cells                []*ResCell  `protobuf:"bytes,7,rep,name=cells" json:"cells,omitempty"`
	Options              []*Label    `protobuf:"bytes,8,rep,name=options" json:"options,omitempty"`
	WanApi               string      `protobuf:"bytes,9,opt,name=wan_api,json=wanApi" json:"wan_api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResZone) Reset()         { *m = ResZone{} }
func (m *ResZone) String() string { return proto.CompactTextString(m) }
func (*ResZone) ProtoMessage()    {}
func (*ResZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{10}
}
func (m *ResZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResZone.Unmarshal(m, b)
}
func (m *ResZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResZone.Marshal(b, m, deterministic)
}
func (dst *ResZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResZone.Merge(dst, src)
}
func (m *ResZone) XXX_Size() int {
	return xxx_messageInfo_ResZone.Size(m)
}
func (m *ResZone) XXX_DiscardUnknown() {
	xxx_messageInfo_ResZone.DiscardUnknown(m)
}

var xxx_messageInfo_ResZone proto.InternalMessageInfo

func (m *ResZone) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResZone) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResZone) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ResZone) GetWanAddrs() []string {
	if m != nil {
		return m.WanAddrs
	}
	return nil
}

func (m *ResZone) GetLanAddrs() []string {
	if m != nil {
		return m.LanAddrs
	}
	return nil
}

func (m *ResZone) GetCells() []*ResCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *ResZone) GetOptions() []*Label {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ResZone) GetWanApi() string {
	if m != nil {
		return m.WanApi
	}
	return ""
}

type ResCell struct {
	Meta                 *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	ZoneId               string      `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Phase                int32       `protobuf:"varint,4,opt,name=phase" json:"phase,omitempty"`
	Description          string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	NodeNum              int32       `protobuf:"varint,6,opt,name=node_num,json=nodeNum" json:"node_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResCell) Reset()         { *m = ResCell{} }
func (m *ResCell) String() string { return proto.CompactTextString(m) }
func (*ResCell) ProtoMessage()    {}
func (*ResCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{11}
}
func (m *ResCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResCell.Unmarshal(m, b)
}
func (m *ResCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResCell.Marshal(b, m, deterministic)
}
func (dst *ResCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResCell.Merge(dst, src)
}
func (m *ResCell) XXX_Size() int {
	return xxx_messageInfo_ResCell.Size(m)
}
func (m *ResCell) XXX_DiscardUnknown() {
	xxx_messageInfo_ResCell.DiscardUnknown(m)
}

var xxx_messageInfo_ResCell proto.InternalMessageInfo

func (m *ResCell) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResCell) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResCell) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResCell) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResCell) GetNodeNum() int32 {
	if m != nil {
		return m.NodeNum
	}
	return 0
}

type ResZoneMasterNode struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Action               uint32   `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResZoneMasterNode) Reset()         { *m = ResZoneMasterNode{} }
func (m *ResZoneMasterNode) String() string { return proto.CompactTextString(m) }
func (*ResZoneMasterNode) ProtoMessage()    {}
func (*ResZoneMasterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{12}
}
func (m *ResZoneMasterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResZoneMasterNode.Unmarshal(m, b)
}
func (m *ResZoneMasterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResZoneMasterNode.Marshal(b, m, deterministic)
}
func (dst *ResZoneMasterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResZoneMasterNode.Merge(dst, src)
}
func (m *ResZoneMasterNode) XXX_Size() int {
	return xxx_messageInfo_ResZoneMasterNode.Size(m)
}
func (m *ResZoneMasterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResZoneMasterNode.DiscardUnknown(m)
}

var xxx_messageInfo_ResZoneMasterNode proto.InternalMessageInfo

func (m *ResZoneMasterNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResZoneMasterNode) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ResZoneMasterNode) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ResZoneMasterList struct {
	Version              uint64               `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Leader               string               `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	Updated              uint64               `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Items                []*ResZoneMasterNode `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResZoneMasterList) Reset()         { *m = ResZoneMasterList{} }
func (m *ResZoneMasterList) String() string { return proto.CompactTextString(m) }
func (*ResZoneMasterList) ProtoMessage()    {}
func (*ResZoneMasterList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_1a3474c74c84cc9f, []int{13}
}
func (m *ResZoneMasterList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResZoneMasterList.Unmarshal(m, b)
}
func (m *ResZoneMasterList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResZoneMasterList.Marshal(b, m, deterministic)
}
func (dst *ResZoneMasterList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResZoneMasterList.Merge(dst, src)
}
func (m *ResZoneMasterList) XXX_Size() int {
	return xxx_messageInfo_ResZoneMasterList.Size(m)
}
func (m *ResZoneMasterList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResZoneMasterList.DiscardUnknown(m)
}

var xxx_messageInfo_ResZoneMasterList proto.InternalMessageInfo

func (m *ResZoneMasterList) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResZoneMasterList) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *ResZoneMasterList) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ResZoneMasterList) GetItems() []*ResZoneMasterNode {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ResHostOperate)(nil), "inapi.ResHostOperate")
	proto.RegisterType((*ResHost)(nil), "inapi.ResHost")
	proto.RegisterType((*ResHostNew)(nil), "inapi.ResHostNew")
	proto.RegisterType((*ResHostList)(nil), "inapi.ResHostList")
	proto.RegisterType((*ResHostSpec)(nil), "inapi.ResHostSpec")
	proto.RegisterType((*ResPlatform)(nil), "inapi.ResPlatform")
	proto.RegisterType((*ResHostResource)(nil), "inapi.ResHostResource")
	proto.RegisterType((*ResHostVolume)(nil), "inapi.ResHostVolume")
	proto.RegisterType((*ResHostStatus)(nil), "inapi.ResHostStatus")
	proto.RegisterType((*ResHostBound)(nil), "inapi.ResHostBound")
	proto.RegisterType((*ResZone)(nil), "inapi.ResZone")
	proto.RegisterType((*ResCell)(nil), "inapi.ResCell")
	proto.RegisterType((*ResZoneMasterNode)(nil), "inapi.ResZoneMasterNode")
	proto.RegisterType((*ResZoneMasterList)(nil), "inapi.ResZoneMasterList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiHostMember service

type ApiHostMemberClient interface {
	HostJoin(ctx context.Context, in *ResHostNew, opts ...grpc.CallOption) (*ResHost, error)
}

type apiHostMemberClient struct {
	cc *grpc.ClientConn
}

func NewApiHostMemberClient(cc *grpc.ClientConn) ApiHostMemberClient {
	return &apiHostMemberClient{cc}
}

func (c *apiHostMemberClient) HostJoin(ctx context.Context, in *ResHostNew, opts ...grpc.CallOption) (*ResHost, error) {
	out := new(ResHost)
	err := grpc.Invoke(ctx, "/inapi.ApiHostMember/HostJoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiHostMember service

type ApiHostMemberServer interface {
	HostJoin(context.Context, *ResHostNew) (*ResHost, error)
}

func RegisterApiHostMemberServer(s *grpc.Server, srv ApiHostMemberServer) {
	s.RegisterService(&_ApiHostMember_serviceDesc, srv)
}

func _ApiHostMember_HostJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHostNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiHostMemberServer).HostJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inapi.ApiHostMember/HostJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiHostMemberServer).HostJoin(ctx, req.(*ResHostNew))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiHostMember_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ApiHostMember",
	HandlerType: (*ApiHostMemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostJoin",
			Handler:    _ApiHostMember_HostJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inapi/cluster.proto",
}

// Client API for ApiZoneMaster service

type ApiZoneMasterClient interface {
	HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResHostBound, error)
}

type apiZoneMasterClient struct {
	cc *grpc.ClientConn
}

func NewApiZoneMasterClient(cc *grpc.ClientConn) ApiZoneMasterClient {
	return &apiZoneMasterClient{cc}
}

func (c *apiZoneMasterClient) HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResHostBound, error) {
	out := new(ResHostBound)
	err := grpc.Invoke(ctx, "/inapi.ApiZoneMaster/HostStatusSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiZoneMaster service

type ApiZoneMasterServer interface {
	HostStatusSync(context.Context, *ResHost) (*ResHostBound, error)
}

func RegisterApiZoneMasterServer(s *grpc.Server, srv ApiZoneMasterServer) {
	s.RegisterService(&_ApiZoneMaster_serviceDesc, srv)
}

func _ApiZoneMaster_HostStatusSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inapi.ApiZoneMaster/HostStatusSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, req.(*ResHost))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiZoneMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ApiZoneMaster",
	HandlerType: (*ApiZoneMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostStatusSync",
			Handler:    _ApiZoneMaster_HostStatusSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inapi/cluster.proto",
}

func init() { proto.RegisterFile("inapi/cluster.proto", fileDescriptor_cluster_1a3474c74c84cc9f) }

var fileDescriptor_cluster_1a3474c74c84cc9f = []byte{
	// 1192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xee, 0xfe, 0x7a, 0x77, 0x36, 0x9b, 0x36, 0xd3, 0xd2, 0x9a, 0x20, 0xa4, 0xc5, 0x2a, 0x25,
	0x42, 0x55, 0x22, 0x6d, 0x55, 0x71, 0x4b, 0x0b, 0x42, 0x0d, 0x34, 0x69, 0x34, 0x51, 0x8b, 0xc4,
	0xcd, 0x6a, 0xd6, 0x3e, 0x28, 0x26, 0xb6, 0x67, 0xe4, 0x19, 0xe7, 0x87, 0x3b, 0x9e, 0x80, 0x17,
	0xe0, 0x3d, 0xe0, 0x51, 0xb8, 0x84, 0x37, 0x41, 0xe7, 0xcc, 0x8c, 0xb3, 0xbb, 0xfd, 0x11, 0x77,
	0x3e, 0xe7, 0xfb, 0xe6, 0x78, 0x7c, 0x7e, 0xbe, 0x63, 0x76, 0x37, 0xaf, 0xa4, 0xce, 0x0f, 0xd2,
	0xa2, 0x31, 0x16, 0xea, 0x7d, 0x5d, 0x2b, 0xab, 0xf8, 0x80, 0x9c, 0xbb, 0x77, 0x1c, 0xb6, 0x94,
	0x06, 0x1c, 0xb0, 0x7b, 0xdb, 0x79, 0xb4, 0xca, 0xbc, 0x63, 0xc7, 0x39, 0x8c, 0x95, 0xd6, 0x38,
	0x57, 0xf2, 0x6f, 0x87, 0x6d, 0x0b, 0x30, 0x2f, 0x94, 0xb1, 0xaf, 0x34, 0xd4, 0xd2, 0x02, 0xbf,
	0xcf, 0x86, 0x32, 0xb5, 0xb9, 0xaa, 0xe2, 0xce, 0xac, 0xb3, 0x37, 0x15, 0xde, 0xe2, 0x0f, 0x58,
	0x94, 0x42, 0x51, 0x2c, 0xf2, 0x2c, 0xee, 0xce, 0x3a, 0x7b, 0x63, 0x31, 0x44, 0xf3, 0x30, 0x43,
	0xe0, 0x57, 0x55, 0x01, 0x02, 0x3d, 0x07, 0xa0, 0x79, 0x98, 0xf1, 0x8f, 0xd9, 0x28, 0xd5, 0xcd,
	0xa2, 0x31, 0x90, 0xc5, 0xfd, 0x59, 0x67, 0x6f, 0x20, 0xa2, 0x54, 0x37, 0xaf, 0x0d, 0x10, 0x54,
	0x42, 0xe9, 0xa0, 0xc1, 0xac, 0xb3, 0xd7, 0x13, 0x51, 0x09, 0x65, 0x80, 0x0a, 0x63, 0x1c, 0x34,
	0x74, 0x50, 0x61, 0x0c, 0x41, 0x9f, 0xb0, 0xb1, 0x56, 0xb5, 0x75, 0x58, 0x34, 0xeb, 0xed, 0x4d,
	0xc5, 0x08, 0x1d, 0x04, 0x3e, 0x60, 0xd1, 0x52, 0x5d, 0x2d, 0xaa, 0xa6, 0x8c, 0x47, 0xf4, 0xb2,
	0xe1, 0x52, 0x5d, 0x1d, 0x37, 0x65, 0xf2, 0x4f, 0x87, 0x45, 0xfe, 0x1b, 0xf9, 0xe7, 0xac, 0x5f,
	0x82, 0x95, 0xf4, 0x69, 0x93, 0xf9, 0xce, 0x3e, 0x65, 0x64, 0xff, 0xd5, 0xf2, 0x17, 0x48, 0xed,
	0x11, 0x58, 0x29, 0x08, 0xe6, 0x07, 0x2c, 0x52, 0x2e, 0x1d, 0xf4, 0xad, 0x93, 0xf9, 0x47, 0x9e,
	0xb9, 0x9e, 0x2b, 0x11, 0x58, 0xfc, 0x11, 0xeb, 0x1b, 0x0d, 0x29, 0x25, 0x60, 0x32, 0xe7, 0xeb,
	0xec, 0x53, 0x0d, 0xa9, 0x20, 0x9c, 0x3f, 0x66, 0x43, 0x4c, 0x7f, 0x63, 0x28, 0x21, 0x93, 0xf9,
	0xbd, 0x0d, 0x26, 0x61, 0xc2, 0x73, 0xf8, 0x17, 0xac, 0xa7, 0x6b, 0x13, 0x0f, 0x66, 0xbd, 0x95,
	0x2b, 0x9c, 0x2c, 0x4f, 0x54, 0x26, 0x40, 0x7b, 0x2e, 0x32, 0x92, 0xbf, 0xba, 0x8c, 0xf9, 0x10,
	0xc7, 0x70, 0xc9, 0x39, 0xeb, 0x57, 0xb2, 0x04, 0xfa, 0xca, 0xb1, 0xa0, 0xe7, 0x95, 0xb2, 0x76,
	0x37, 0xcb, 0xfa, 0xee, 0xea, 0xad, 0xd4, 0xbb, 0xbf, 0x56, 0xef, 0x84, 0x4d, 0x35, 0x40, 0xbd,
	0x28, 0x64, 0xb5, 0x90, 0x59, 0x56, 0x53, 0x01, 0xc7, 0x62, 0x82, 0xce, 0x97, 0xb2, 0x7a, 0x96,
	0x65, 0x35, 0xff, 0x94, 0x31, 0x03, 0x69, 0x0d, 0x76, 0x71, 0x0e, 0xd7, 0x54, 0xc6, 0xb1, 0x18,
	0x3b, 0xcf, 0x0f, 0x70, 0xcd, 0x3f, 0x63, 0x5b, 0xf4, 0xd2, 0x52, 0x62, 0x23, 0x1b, 0xaa, 0xe5,
	0x58, 0x4c, 0xd0, 0x77, 0xe4, 0x5c, 0xfc, 0x80, 0xdd, 0x73, 0xf7, 0x92, 0xe5, 0xc2, 0x40, 0x7d,
	0x91, 0xa7, 0xb0, 0x68, 0xea, 0x82, 0x6a, 0x3b, 0x16, 0x3b, 0x74, 0x49, 0x59, 0x9e, 0x3a, 0xe4,
	0x75, 0x5d, 0xf0, 0xa7, 0xec, 0x81, 0x3b, 0x50, 0x69, 0x99, 0x9e, 0xaf, 0x9d, 0x19, 0xd3, 0x19,
	0x8a, 0x77, 0x48, 0xe8, 0xcd, 0xb1, 0xe4, 0x09, 0x9b, 0xf8, 0xcc, 0xbd, 0xcc, 0x8d, 0xe5, 0x0f,
	0xd9, 0x20, 0xb7, 0x50, 0x9a, 0xb8, 0x4b, 0x49, 0xdf, 0x5e, 0xaf, 0x8f, 0x70, 0x60, 0xf2, 0x77,
	0xb7, 0x3d, 0x85, 0xc5, 0xe5, 0xfb, 0x6c, 0xa4, 0x0b, 0x69, 0x7f, 0x56, 0x75, 0xe9, 0x1b, 0x66,
	0xa5, 0x05, 0x4e, 0x3c, 0x22, 0x5a, 0x0e, 0x9f, 0xb3, 0x51, 0x2a, 0xb5, 0x4c, 0x73, 0x7b, 0xed,
	0x5b, 0xe6, 0xfe, 0xc6, 0x8b, 0xc0, 0xa8, 0xa6, 0x4e, 0x41, 0xb4, 0x3c, 0x6c, 0xfe, 0x33, 0x6b,
	0xf5, 0x02, 0x1b, 0x9e, 0x52, 0x3e, 0x15, 0x23, 0x74, 0x9c, 0xa8, 0xda, 0xbe, 0x5d, 0x93, 0xe1,
	0xdb, 0x35, 0x09, 0x9c, 0xcb, 0xc0, 0x89, 0x6e, 0x38, 0x3f, 0x7a, 0xce, 0x63, 0xc6, 0xe1, 0x4a,
	0x2f, 0x32, 0x95, 0x9e, 0x43, 0xbd, 0xb8, 0x80, 0xda, 0x60, 0xc7, 0x30, 0x22, 0xde, 0x81, 0x2b,
	0xfd, 0x2d, 0x01, 0x6f, 0x9c, 0x9f, 0x3f, 0x62, 0xb7, 0x91, 0x5d, 0x9f, 0xdb, 0x96, 0x3a, 0x21,
	0xea, 0x14, 0xae, 0xb4, 0x38, 0xb7, 0x81, 0xf7, 0x25, 0xdb, 0x41, 0x9e, 0x56, 0x4d, 0x7a, 0xd6,
	0x32, 0xb7, 0x88, 0x89, 0x01, 0x4e, 0xd0, 0xef, 0xb9, 0xc9, 0x21, 0x65, 0x36, 0xe4, 0x8c, 0x6f,
	0xb3, 0xae, 0x32, 0xbe, 0x91, 0xbb, 0xca, 0x60, 0x1b, 0x9f, 0x43, 0x5d, 0x41, 0x11, 0x44, 0xc8,
	0x59, 0xd8, 0xf2, 0xb2, 0x4e, 0xcf, 0x7c, 0x0f, 0xd3, 0x73, 0xf2, 0x94, 0xdd, 0xde, 0x48, 0x27,
	0xbf, 0xc3, 0x7a, 0x25, 0x94, 0x14, 0xaf, 0x27, 0xf0, 0x11, 0x3d, 0xa9, 0x6e, 0x28, 0xda, 0x40,
	0xe0, 0x63, 0x72, 0xc4, 0xa6, 0xfe, 0xd8, 0x1b, 0x55, 0x34, 0x25, 0xbc, 0x73, 0x9c, 0xee, 0xb1,
	0x81, 0x55, 0x56, 0xba, 0x6b, 0xf4, 0x85, 0x33, 0x90, 0x49, 0xda, 0xd4, 0x23, 0x27, 0x3d, 0x27,
	0x7f, 0x76, 0xda, 0x78, 0x6e, 0x64, 0xf1, 0xac, 0x3e, 0x93, 0x26, 0x04, 0x74, 0x06, 0x7e, 0x59,
	0xa3, 0x6d, 0x5e, 0x42, 0x18, 0x50, 0x67, 0xf1, 0x7d, 0x16, 0x5d, 0xd0, 0x3d, 0x4c, 0xdc, 0xa3,
	0x9e, 0xdc, 0xd0, 0x0c, 0x77, 0x49, 0x11, 0x48, 0x7c, 0x9f, 0x0d, 0x48, 0xe1, 0xbd, 0xc2, 0xc4,
	0xad, 0x6c, 0xe0, 0xdb, 0xcd, 0xa9, 0x2c, 0x75, 0x01, 0xdf, 0x01, 0x64, 0xc2, 0xd1, 0x78, 0xcc,
	0xa2, 0x46, 0x67, 0xd2, 0x7a, 0x25, 0x9e, 0x8a, 0x60, 0xa2, 0x70, 0x6e, 0xf9, 0x97, 0x3c, 0x57,
	0x4d, 0x95, 0xf1, 0x39, 0x8b, 0xc2, 0xc4, 0x76, 0xd7, 0x82, 0x0b, 0x30, 0x3f, 0xb5, 0xb3, 0x8b,
	0x73, 0x24, 0x02, 0x11, 0xe5, 0xdc, 0xd5, 0x3e, 0x73, 0x42, 0x36, 0x16, 0x11, 0x95, 0x3c, 0x33,
	0x1f, 0x9a, 0xd8, 0xe8, 0xfd, 0x13, 0x1b, 0xba, 0x0e, 0xc5, 0xbe, 0x86, 0x52, 0x5d, 0x80, 0x89,
	0x47, 0x14, 0x18, 0xbb, 0xee, 0xb9, 0xba, 0x12, 0xce, 0x89, 0xfd, 0x1e, 0x78, 0xc6, 0x2a, 0x6d,
	0xe2, 0xb1, 0x53, 0x19, 0xc7, 0x3a, 0x45, 0x57, 0xf2, 0x5b, 0x97, 0x76, 0x03, 0x5e, 0xbe, 0xdd,
	0x0d, 0xdd, 0x0f, 0xef, 0x86, 0xb6, 0x7a, 0x3d, 0x6a, 0x19, 0x5f, 0xbd, 0x98, 0x45, 0xa6, 0x29,
	0x4b, 0x59, 0x5f, 0x7b, 0xb5, 0x0c, 0x26, 0xce, 0x6d, 0x98, 0xb8, 0x90, 0x81, 0xd1, 0xa5, 0x1b,
	0x37, 0x83, 0x60, 0xd1, 0x82, 0x43, 0x07, 0x16, 0x01, 0x7c, 0xc8, 0x06, 0x28, 0xb9, 0x4e, 0x1e,
	0xd7, 0xb4, 0xe8, 0x1b, 0x28, 0x0a, 0xe1, 0x40, 0xfe, 0x08, 0x77, 0x15, 0x4a, 0xb9, 0x4b, 0xc3,
	0x64, 0xbe, 0xe5, 0x79, 0x2f, 0xe5, 0x12, 0x0a, 0x11, 0x40, 0xd4, 0x73, 0xba, 0x87, 0xce, 0xbd,
	0x1e, 0x0e, 0xf1, 0x16, 0x3a, 0x4f, 0xfe, 0x70, 0xfb, 0x11, 0x63, 0xfe, 0xdf, 0x1c, 0xbc, 0x77,
	0x69, 0xb4, 0xc9, 0xe9, 0xaf, 0x26, 0x67, 0xc6, 0x26, 0x19, 0x98, 0xb4, 0xce, 0xe9, 0x2a, 0x61,
	0x5f, 0xac, 0xb8, 0xb0, 0x4b, 0x2a, 0x95, 0x01, 0x6d, 0xef, 0xa1, 0xfb, 0x55, 0x40, 0x1b, 0xd7,
	0xf7, 0x2b, 0xb6, 0xb3, 0xd6, 0x5e, 0xc7, 0x2a, 0x03, 0x94, 0x85, 0x3c, 0x0b, 0xb2, 0x90, 0x67,
	0x34, 0xfe, 0x28, 0x69, 0x5d, 0x3f, 0xfe, 0xa8, 0x65, 0x37, 0x1b, 0xaf, 0xb7, 0xba, 0xf1, 0x92,
	0xdf, 0x3b, 0x1b, 0x11, 0x49, 0xf8, 0x63, 0x16, 0x05, 0x65, 0xea, 0xd0, 0xf4, 0x06, 0x13, 0xe3,
	0x14, 0x20, 0x33, 0x08, 0xd1, 0xbd, 0xb5, 0x3a, 0x38, 0x6e, 0xde, 0x83, 0x89, 0x23, 0xe8, 0x96,
	0x48, 0x9f, 0x0a, 0xf2, 0xce, 0x29, 0xc1, 0xcf, 0xf0, 0xeb, 0x64, 0xfe, 0x35, 0x9b, 0x3e, 0xd3,
	0x39, 0xce, 0xd9, 0x11, 0x94, 0x4b, 0xa8, 0xf9, 0x01, 0x1b, 0xa1, 0xf5, 0xbd, 0xca, 0x2b, 0xbe,
	0xb3, 0x3e, 0xee, 0xc7, 0x70, 0xb9, 0xbb, 0xb1, 0x95, 0x92, 0x5b, 0xf3, 0x17, 0x14, 0xe1, 0x26,
	0x3a, 0xff, 0x8a, 0x6d, 0xdf, 0x28, 0xce, 0xe9, 0x75, 0x95, 0xf2, 0x8d, 0x43, 0xbb, 0x77, 0xd7,
	0x6d, 0x9a, 0xf0, 0xe4, 0xd6, 0x72, 0x48, 0x3f, 0x86, 0x4f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x6e, 0x48, 0x42, 0xa2, 0x6c, 0x0a, 0x00, 0x00,
}
