// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inapi/mail.proto

package inapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailType int32

const (
	MailType_TEXT MailType = 0
	MailType_HTML MailType = 1
)

var MailType_name = map[int32]string{
	0: "TEXT",
	1: "HTML",
}

var MailType_value = map[string]int32{
	"TEXT": 0,
	"HTML": 1,
}

func (x MailType) String() string {
	return proto.EnumName(MailType_name, int32(x))
}

func (MailType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{0}
}

type MailTemplate struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty" toml:"body,omitempty"`
	Type                 MailType `protobuf:"varint,4,opt,name=type,proto3,enum=inapi.MailType" json:"type,omitempty" toml:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-"`
	XXX_unrecognized     []byte   `json:"-" toml:"-"`
	XXX_sizecache        int32    `json:"-" toml:"-"`
}

func (m *MailTemplate) Reset()         { *m = MailTemplate{} }
func (m *MailTemplate) String() string { return proto.CompactTextString(m) }
func (*MailTemplate) ProtoMessage()    {}
func (*MailTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{0}
}

func (m *MailTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailTemplate.Unmarshal(m, b)
}
func (m *MailTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailTemplate.Marshal(b, m, deterministic)
}
func (m *MailTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailTemplate.Merge(m, src)
}
func (m *MailTemplate) XXX_Size() int {
	return xxx_messageInfo_MailTemplate.Size(m)
}
func (m *MailTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_MailTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_MailTemplate proto.InternalMessageInfo

func (m *MailTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MailTemplate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailTemplate) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MailTemplate) GetType() MailType {
	if m != nil {
		return m.Type
	}
	return MailType_TEXT
}

type MailEntry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	ToUser               string   `protobuf:"bytes,3,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty" toml:"to_user,omitempty"`
	FromUser             string   `protobuf:"bytes,5,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty" toml:"from_user,omitempty"`
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty"`
	Body                 string   `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty" toml:"body,omitempty"`
	Type                 MailType `protobuf:"varint,11,opt,name=type,proto3,enum=inapi.MailType" json:"type,omitempty" toml:"type,omitempty"`
	Created              uint32   `protobuf:"varint,14,opt,name=created,proto3" json:"created,omitempty" toml:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-"`
	XXX_unrecognized     []byte   `json:"-" toml:"-"`
	XXX_sizecache        int32    `json:"-" toml:"-"`
}

func (m *MailEntry) Reset()         { *m = MailEntry{} }
func (m *MailEntry) String() string { return proto.CompactTextString(m) }
func (*MailEntry) ProtoMessage()    {}
func (*MailEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{1}
}

func (m *MailEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailEntry.Unmarshal(m, b)
}
func (m *MailEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailEntry.Marshal(b, m, deterministic)
}
func (m *MailEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailEntry.Merge(m, src)
}
func (m *MailEntry) XXX_Size() int {
	return xxx_messageInfo_MailEntry.Size(m)
}
func (m *MailEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MailEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MailEntry proto.InternalMessageInfo

func (m *MailEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MailEntry) GetToUser() string {
	if m != nil {
		return m.ToUser
	}
	return ""
}

func (m *MailEntry) GetFromUser() string {
	if m != nil {
		return m.FromUser
	}
	return ""
}

func (m *MailEntry) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailEntry) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MailEntry) GetType() MailType {
	if m != nil {
		return m.Type
	}
	return MailType_TEXT
}

func (m *MailEntry) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

type MailPodStatus struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	User                 string               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty" toml:"user,omitempty"`
	Items                []*MailPodStatus_Pod `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
	Created              uint32               `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty" toml:"created,omitempty"`
	WeekNum              uint32               `protobuf:"varint,6,opt,name=week_num,json=weekNum,proto3" json:"week_num,omitempty" toml:"week_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" toml:"-"`
	XXX_unrecognized     []byte               `json:"-" toml:"-"`
	XXX_sizecache        int32                `json:"-" toml:"-"`
}

func (m *MailPodStatus) Reset()         { *m = MailPodStatus{} }
func (m *MailPodStatus) String() string { return proto.CompactTextString(m) }
func (*MailPodStatus) ProtoMessage()    {}
func (*MailPodStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{2}
}

func (m *MailPodStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailPodStatus.Unmarshal(m, b)
}
func (m *MailPodStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailPodStatus.Marshal(b, m, deterministic)
}
func (m *MailPodStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailPodStatus.Merge(m, src)
}
func (m *MailPodStatus) XXX_Size() int {
	return xxx_messageInfo_MailPodStatus.Size(m)
}
func (m *MailPodStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MailPodStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MailPodStatus proto.InternalMessageInfo

func (m *MailPodStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MailPodStatus) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MailPodStatus) GetItems() []*MailPodStatus_Pod {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *MailPodStatus) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *MailPodStatus) GetWeekNum() uint32 {
	if m != nil {
		return m.WeekNum
	}
	return 0
}

type MailPodStatus_PodReplica struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	VolUsed              int64    `protobuf:"varint,2,opt,name=vol_used,json=volUsed,proto3" json:"vol_used,omitempty" toml:"vol_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" toml:"-"`
	XXX_unrecognized     []byte   `json:"-" toml:"-"`
	XXX_sizecache        int32    `json:"-" toml:"-"`
}

func (m *MailPodStatus_PodReplica) Reset()         { *m = MailPodStatus_PodReplica{} }
func (m *MailPodStatus_PodReplica) String() string { return proto.CompactTextString(m) }
func (*MailPodStatus_PodReplica) ProtoMessage()    {}
func (*MailPodStatus_PodReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{2, 0}
}

func (m *MailPodStatus_PodReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailPodStatus_PodReplica.Unmarshal(m, b)
}
func (m *MailPodStatus_PodReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailPodStatus_PodReplica.Marshal(b, m, deterministic)
}
func (m *MailPodStatus_PodReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailPodStatus_PodReplica.Merge(m, src)
}
func (m *MailPodStatus_PodReplica) XXX_Size() int {
	return xxx_messageInfo_MailPodStatus_PodReplica.Size(m)
}
func (m *MailPodStatus_PodReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_MailPodStatus_PodReplica.DiscardUnknown(m)
}

var xxx_messageInfo_MailPodStatus_PodReplica proto.InternalMessageInfo

func (m *MailPodStatus_PodReplica) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MailPodStatus_PodReplica) GetVolUsed() int64 {
	if m != nil {
		return m.VolUsed
	}
	return 0
}

type MailPodStatus_Pod struct {
	PodId                string                      `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty" toml:"pod_id,omitempty"`
	ZoneName             string                      `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty" toml:"zone_name,omitempty"`
	CellName             string                      `protobuf:"bytes,3,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty" toml:"cell_name,omitempty"`
	SpecCpu              int32                       `protobuf:"varint,5,opt,name=spec_cpu,json=specCpu,proto3" json:"spec_cpu,omitempty" toml:"spec_cpu,omitempty"`
	SpecMem              int32                       `protobuf:"varint,6,opt,name=spec_mem,json=specMem,proto3" json:"spec_mem,omitempty" toml:"spec_mem,omitempty"`
	SpecVol              int32                       `protobuf:"varint,7,opt,name=spec_vol,json=specVol,proto3" json:"spec_vol,omitempty" toml:"spec_vol,omitempty"`
	PaymentCycleAmount   float32                     `protobuf:"fixed32,8,opt,name=payment_cycle_amount,json=paymentCycleAmount,proto3" json:"payment_cycle_amount,omitempty" toml:"payment_cycle_amount,omitempty"`
	Reps                 []*MailPodStatus_PodReplica `protobuf:"bytes,15,rep,name=reps,proto3" json:"reps,omitempty" toml:"reps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-" toml:"-"`
	XXX_unrecognized     []byte                      `json:"-" toml:"-"`
	XXX_sizecache        int32                       `json:"-" toml:"-"`
}

func (m *MailPodStatus_Pod) Reset()         { *m = MailPodStatus_Pod{} }
func (m *MailPodStatus_Pod) String() string { return proto.CompactTextString(m) }
func (*MailPodStatus_Pod) ProtoMessage()    {}
func (*MailPodStatus_Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_3787a141cc5331ee, []int{2, 1}
}

func (m *MailPodStatus_Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailPodStatus_Pod.Unmarshal(m, b)
}
func (m *MailPodStatus_Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailPodStatus_Pod.Marshal(b, m, deterministic)
}
func (m *MailPodStatus_Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailPodStatus_Pod.Merge(m, src)
}
func (m *MailPodStatus_Pod) XXX_Size() int {
	return xxx_messageInfo_MailPodStatus_Pod.Size(m)
}
func (m *MailPodStatus_Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_MailPodStatus_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_MailPodStatus_Pod proto.InternalMessageInfo

func (m *MailPodStatus_Pod) GetPodId() string {
	if m != nil {
		return m.PodId
	}
	return ""
}

func (m *MailPodStatus_Pod) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *MailPodStatus_Pod) GetCellName() string {
	if m != nil {
		return m.CellName
	}
	return ""
}

func (m *MailPodStatus_Pod) GetSpecCpu() int32 {
	if m != nil {
		return m.SpecCpu
	}
	return 0
}

func (m *MailPodStatus_Pod) GetSpecMem() int32 {
	if m != nil {
		return m.SpecMem
	}
	return 0
}

func (m *MailPodStatus_Pod) GetSpecVol() int32 {
	if m != nil {
		return m.SpecVol
	}
	return 0
}

func (m *MailPodStatus_Pod) GetPaymentCycleAmount() float32 {
	if m != nil {
		return m.PaymentCycleAmount
	}
	return 0
}

func (m *MailPodStatus_Pod) GetReps() []*MailPodStatus_PodReplica {
	if m != nil {
		return m.Reps
	}
	return nil
}

func init() {
	proto.RegisterEnum("inapi.MailType", MailType_name, MailType_value)
	proto.RegisterType((*MailTemplate)(nil), "inapi.MailTemplate")
	proto.RegisterType((*MailEntry)(nil), "inapi.MailEntry")
	proto.RegisterType((*MailPodStatus)(nil), "inapi.MailPodStatus")
	proto.RegisterType((*MailPodStatus_PodReplica)(nil), "inapi.MailPodStatus.PodReplica")
	proto.RegisterType((*MailPodStatus_Pod)(nil), "inapi.MailPodStatus.Pod")
}

func init() { proto.RegisterFile("inapi/mail.proto", fileDescriptor_3787a141cc5331ee) }

var fileDescriptor_3787a141cc5331ee = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0x6c, 0x27, 0xce, 0x94, 0xa4, 0xd1, 0xaa, 0x88, 0x4d, 0x2b, 0x41, 0x14, 0x2e,
	0x11, 0x87, 0x80, 0xda, 0x03, 0x67, 0x54, 0x55, 0x02, 0x89, 0x54, 0x91, 0x49, 0x11, 0x37, 0xcb,
	0xf5, 0x0e, 0x92, 0xc5, 0xae, 0x77, 0xb1, 0xd7, 0x41, 0xe6, 0x21, 0x78, 0x20, 0x1e, 0x87, 0x27,
	0x41, 0x3b, 0x9b, 0x86, 0x20, 0x0a, 0xb7, 0x99, 0xf9, 0x46, 0x3b, 0xff, 0xfc, 0x1e, 0xc3, 0xa4,
	0xac, 0x72, 0x53, 0xbe, 0x50, 0x79, 0x29, 0x97, 0xa6, 0xd6, 0x56, 0xb3, 0x98, 0x2a, 0xf3, 0x2f,
	0xf0, 0x70, 0x95, 0x97, 0x72, 0x83, 0xca, 0xc8, 0xdc, 0x22, 0x63, 0x10, 0x55, 0xb9, 0x42, 0x1e,
	0xcc, 0x82, 0xc5, 0x30, 0xa5, 0x98, 0x9d, 0x40, 0x6c, 0x4b, 0x2b, 0x91, 0xf7, 0xa8, 0xe8, 0x13,
	0xd7, 0x79, 0xab, 0x45, 0xc7, 0x43, 0xdf, 0xe9, 0x62, 0xf6, 0x0c, 0x22, 0xdb, 0x19, 0xe4, 0xd1,
	0x2c, 0x58, 0x8c, 0xcf, 0x8f, 0x97, 0x34, 0x63, 0x49, 0x03, 0x3a, 0x83, 0x29, 0xc1, 0xf9, 0x8f,
	0x00, 0x86, 0xae, 0x74, 0x55, 0xd9, 0xba, 0x63, 0x63, 0xe8, 0x95, 0x62, 0x37, 0xae, 0x57, 0x0a,
	0xf6, 0x18, 0x06, 0x56, 0x67, 0x6d, 0x83, 0xf5, 0xee, 0xe5, 0xbe, 0xd5, 0x37, 0x0d, 0xd6, 0xec,
	0x0c, 0x86, 0x9f, 0x6a, 0xad, 0x3c, 0x8a, 0x09, 0x25, 0xae, 0x40, 0x70, 0x2f, 0x31, 0xb9, 0x4f,
	0xe2, 0xf0, 0x1e, 0x89, 0x47, 0xff, 0x91, 0xc8, 0x38, 0x0c, 0x8a, 0x1a, 0x73, 0x8b, 0x82, 0x8f,
	0x67, 0xc1, 0x62, 0x94, 0xde, 0xa5, 0xf3, 0x9f, 0x21, 0x8c, 0x5c, 0xf3, 0x5a, 0x8b, 0xf7, 0x36,
	0xb7, 0x6d, 0xf3, 0xd7, 0x02, 0x0c, 0x22, 0x92, 0xe8, 0xcd, 0xa2, 0x98, 0x2d, 0x21, 0x2e, 0x2d,
	0xaa, 0x86, 0x87, 0xb3, 0x70, 0x71, 0x74, 0xce, 0x0f, 0xa6, 0xee, 0x1f, 0x5a, 0xae, 0xb5, 0x48,
	0x7d, 0xdb, 0xe1, 0xfc, 0xf8, 0x8f, 0xf9, 0x6c, 0x0a, 0xc9, 0x57, 0xc4, 0xcf, 0x59, 0xd5, 0x2a,
	0xde, 0xf7, 0xc8, 0xe5, 0xd7, 0xad, 0x3a, 0x7d, 0x05, 0xe0, 0x9e, 0x40, 0x23, 0xcb, 0x22, 0x3f,
	0x90, 0x35, 0x22, 0x59, 0x53, 0x48, 0xb6, 0x5a, 0x3a, 0xf7, 0x04, 0x49, 0x0b, 0xd3, 0xc1, 0x56,
	0xcb, 0x9b, 0x06, 0xc5, 0xe9, 0xf7, 0x1e, 0x84, 0x6b, 0x2d, 0xd8, 0x23, 0xe8, 0x1b, 0x2d, 0xb2,
	0xfd, 0x36, 0xb1, 0xd1, 0xe2, 0xad, 0x70, 0xc6, 0x7f, 0xd3, 0x15, 0x66, 0x74, 0x17, 0x7e, 0xab,
	0xc4, 0x15, 0xae, 0xdd, 0x6d, 0x9c, 0xc1, 0xb0, 0x40, 0x29, 0x3d, 0xf4, 0x1f, 0x2c, 0x71, 0x05,
	0x82, 0x53, 0x48, 0x1a, 0x83, 0x45, 0x56, 0x98, 0x96, 0xf6, 0x88, 0xd3, 0x81, 0xcb, 0x2f, 0x4d,
	0xbb, 0x47, 0x0a, 0xfd, 0x1e, 0x3b, 0xb4, 0x42, 0xb5, 0x47, 0x5b, 0x2d, 0xf9, 0xe0, 0x37, 0xfa,
	0xa0, 0x25, 0x7b, 0x09, 0x27, 0x26, 0xef, 0x14, 0x56, 0x36, 0x2b, 0xba, 0x42, 0x62, 0x96, 0x2b,
	0xdd, 0x56, 0x96, 0xbe, 0x7a, 0x2f, 0x65, 0x3b, 0x76, 0xe9, 0xd0, 0x6b, 0x22, 0xec, 0x02, 0xa2,
	0x1a, 0x4d, 0xc3, 0x8f, 0xc9, 0xf8, 0xa7, 0xff, 0x34, 0xde, 0xbb, 0x96, 0x52, 0xf3, 0xf3, 0x27,
	0x90, 0xdc, 0x1d, 0x04, 0x4b, 0x20, 0xda, 0x5c, 0x7d, 0xdc, 0x4c, 0x1e, 0xb8, 0xe8, 0xcd, 0x66,
	0xf5, 0x6e, 0x12, 0xdc, 0xf6, 0xe9, 0x17, 0xba, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0xce, 0xdd,
	0x0a, 0x09, 0x56, 0x03, 0x00, 0x00,
}
