// Code generated by github.com/hooto/protobuf_slice
// source: operator.proto
// DO NOT EDIT!

package inapi

import "sync"

var object_slice_mu_PbOpLogEntry sync.RWMutex

func (it *PbOpLogEntry) Equal(it2 *PbOpLogEntry) bool {
	if it2 == nil ||
		it.Name != it2.Name ||
		it.Status != it2.Status ||
		it.Updated != it2.Updated ||
		it.Message != it2.Message {
		return false
	}
	return true
}

func (it *PbOpLogEntry) Sync(it2 *PbOpLogEntry) bool {
	if it2 == nil {
		return false
	}
	if it.Equal(it2) {
		return false
	}
	*it = *it2
	return true
}

func PbOpLogEntrySliceGet(ls []*PbOpLogEntry, arg_name string) *PbOpLogEntry {
	object_slice_mu_PbOpLogEntry.RLock()
	defer object_slice_mu_PbOpLogEntry.RUnlock()

	for _, v := range ls {
		if v.Name == arg_name {
			return v
		}
	}
	return nil
}

func PbOpLogEntrySliceEqual(ls, ls2 []*PbOpLogEntry) bool {
	object_slice_mu_PbOpLogEntry.RLock()
	defer object_slice_mu_PbOpLogEntry.RUnlock()

	if len(ls) != len(ls2) {
		return false
	}
	hit := false
	for _, v := range ls {
		hit = false
		for _, v2 := range ls2 {
			if v.Name != v2.Name {
				continue
			}
			if !v.Equal(v2) {
				return false
			}
			hit = true
			break
		}
		if !hit {
			return false
		}
	}
	return true
}

func PbOpLogEntrySliceSync(ls []*PbOpLogEntry, it2 *PbOpLogEntry) ([]*PbOpLogEntry, bool) {
	if it2 == nil {
		return ls, false
	}
	object_slice_mu_PbOpLogEntry.Lock()
	defer object_slice_mu_PbOpLogEntry.Unlock()

	hit := false
	changed := false
	for i, v := range ls {
		if v.Name != it2.Name {
			continue
		}
		if !v.Equal(it2) {
			ls[i], changed = it2, true
		}
		hit = true
		break
	}
	if !hit {
		ls = append(ls, it2)
		changed = true
	}
	return ls, changed
}

func PbOpLogEntrySliceSyncSlice(ls, ls2 []*PbOpLogEntry) ([]*PbOpLogEntry, bool) {
	if PbOpLogEntrySliceEqual(ls, ls2) {
		return ls, false
	}
	return ls2, true
}

var object_slice_mu_PbOpLogSets sync.RWMutex

func (it *PbOpLogSets) Equal(it2 *PbOpLogSets) bool {
	if it2 == nil ||
		it.Name != it2.Name ||
		it.Version != it2.Version ||
		!PbOpLogEntrySliceEqual(it.Items, it2.Items) {
		return false
	}
	return true
}

func (it *PbOpLogSets) Sync(it2 *PbOpLogSets) bool {
	if it2 == nil {
		return false
	}
	if it.Equal(it2) {
		return false
	}
	*it = *it2
	return true
}

func PbOpLogSetsSliceGet(ls []*PbOpLogSets, arg_name string) *PbOpLogSets {
	object_slice_mu_PbOpLogSets.RLock()
	defer object_slice_mu_PbOpLogSets.RUnlock()

	for _, v := range ls {
		if v.Name == arg_name {
			return v
		}
	}
	return nil
}

func PbOpLogSetsSliceEqual(ls, ls2 []*PbOpLogSets) bool {
	object_slice_mu_PbOpLogSets.RLock()
	defer object_slice_mu_PbOpLogSets.RUnlock()

	if len(ls) != len(ls2) {
		return false
	}
	hit := false
	for _, v := range ls {
		hit = false
		for _, v2 := range ls2 {
			if v.Name != v2.Name {
				continue
			}
			if !v.Equal(v2) {
				return false
			}
			hit = true
			break
		}
		if !hit {
			return false
		}
	}
	return true
}

func PbOpLogSetsSliceSync(ls []*PbOpLogSets, it2 *PbOpLogSets) ([]*PbOpLogSets, bool) {
	if it2 == nil {
		return ls, false
	}
	object_slice_mu_PbOpLogSets.Lock()
	defer object_slice_mu_PbOpLogSets.Unlock()

	hit := false
	changed := false
	for i, v := range ls {
		if v.Name != it2.Name {
			continue
		}
		if !v.Equal(it2) {
			ls[i], changed = it2, true
		}
		hit = true
		break
	}
	if !hit {
		ls = append(ls, it2)
		changed = true
	}
	return ls, changed
}

func PbOpLogSetsSliceSyncSlice(ls, ls2 []*PbOpLogSets) ([]*PbOpLogSets, bool) {
	if PbOpLogSetsSliceEqual(ls, ls2) {
		return ls, false
	}
	return ls2, true
}
