// Code generated by protoc-gen-go.
// source: pbtypes.proto
// DO NOT EDIT!

/*
Package losapi is a generated protocol buffer package.

It is generated from these files:
	pbtypes.proto

It has these top-level messages:
	ErrorMeta
	TypeMeta
	ObjectMeta
	Label
	ResHostOperate
	ResHost
	ResHostList
	ResHostSpec
	ResPlatform
	ResHostResource
	ResHostStatus
	ResZone
	ResCell
	ResZoneMasterNode
	ResZoneMasterList
*/
package losapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperateAction int32

const (
	OperateAction_Unknown OperateAction = 0
	OperateAction_Start   OperateAction = 1
	OperateAction_Stop    OperateAction = 2
)

var OperateAction_name = map[int32]string{
	0: "Unknown",
	1: "Start",
	2: "Stop",
}
var OperateAction_value = map[string]int32{
	"Unknown": 0,
	"Start":   1,
	"Stop":    2,
}

func (x OperateAction) String() string {
	return proto.EnumName(OperateAction_name, int32(x))
}
func (OperateAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorMeta struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorMeta) Reset()                    { *m = ErrorMeta{} }
func (m *ErrorMeta) String() string            { return proto.CompactTextString(m) }
func (*ErrorMeta) ProtoMessage()               {}
func (*ErrorMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorMeta) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorMeta) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TypeMeta struct {
	Kind  string     `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Error *ErrorMeta `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *TypeMeta) Reset()                    { *m = TypeMeta{} }
func (m *TypeMeta) String() string            { return proto.CompactTextString(m) }
func (*TypeMeta) ProtoMessage()               {}
func (*TypeMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeMeta) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TypeMeta) GetError() *ErrorMeta {
	if m != nil {
		return m.Error
	}
	return nil
}

type ObjectMeta struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Created uint64 `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Updated uint64 `protobuf:"varint,4,opt,name=updated" json:"updated,omitempty"`
}

func (m *ObjectMeta) Reset()                    { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string            { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()               {}
func (*ObjectMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ObjectMeta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMeta) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ObjectMeta) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Label struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// host
type ResHostOperate struct {
	Action   uint32   `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	CellId   string   `protobuf:"bytes,2,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	ZoneId   string   `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	CpuUsed  int64    `protobuf:"varint,4,opt,name=cpu_used,json=cpuUsed" json:"cpu_used,omitempty"`
	RamUsed  int64    `protobuf:"varint,5,opt,name=ram_used,json=ramUsed" json:"ram_used,omitempty"`
	LssUsed  int64    `protobuf:"varint,6,opt,name=lss_used,json=lssUsed" json:"lss_used,omitempty"`
	PortUsed []uint32 `protobuf:"varint,7,rep,packed,name=port_used,json=portUsed" json:"port_used,omitempty"`
}

func (m *ResHostOperate) Reset()                    { *m = ResHostOperate{} }
func (m *ResHostOperate) String() string            { return proto.CompactTextString(m) }
func (*ResHostOperate) ProtoMessage()               {}
func (*ResHostOperate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResHostOperate) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ResHostOperate) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ResHostOperate) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResHostOperate) GetCpuUsed() int64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *ResHostOperate) GetRamUsed() int64 {
	if m != nil {
		return m.RamUsed
	}
	return 0
}

func (m *ResHostOperate) GetLssUsed() int64 {
	if m != nil {
		return m.LssUsed
	}
	return 0
}

func (m *ResHostOperate) GetPortUsed() []uint32 {
	if m != nil {
		return m.PortUsed
	}
	return nil
}

type ResHost struct {
	Meta    *ObjectMeta     `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Operate *ResHostOperate `protobuf:"bytes,2,opt,name=operate" json:"operate,omitempty"`
	Spec    *ResHostSpec    `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status  *ResHostStatus  `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *ResHost) Reset()                    { *m = ResHost{} }
func (m *ResHost) String() string            { return proto.CompactTextString(m) }
func (*ResHost) ProtoMessage()               {}
func (*ResHost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResHost) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResHost) GetOperate() *ResHostOperate {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *ResHost) GetSpec() *ResHostSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ResHost) GetStatus() *ResHostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ResHostList struct {
	Items []*ResHost `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *ResHostList) Reset()                    { *m = ResHostList{} }
func (m *ResHostList) String() string            { return proto.CompactTextString(m) }
func (*ResHostList) ProtoMessage()               {}
func (*ResHostList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResHostList) GetItems() []*ResHost {
	if m != nil {
		return m.Items
	}
	return nil
}

type ResHostSpec struct {
	Platform    *ResPlatform     `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Capacity    *ResHostResource `protobuf:"bytes,3,opt,name=capacity" json:"capacity,omitempty"`
	HttpPort    uint32           `protobuf:"varint,5,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
	PeerLanAddr string           `protobuf:"bytes,6,opt,name=peer_lan_addr,json=peerLanAddr" json:"peer_lan_addr,omitempty"`
	PeerWanAddr string           `protobuf:"bytes,7,opt,name=peer_wan_addr,json=peerWanAddr" json:"peer_wan_addr,omitempty"`
}

func (m *ResHostSpec) Reset()                    { *m = ResHostSpec{} }
func (m *ResHostSpec) String() string            { return proto.CompactTextString(m) }
func (*ResHostSpec) ProtoMessage()               {}
func (*ResHostSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResHostSpec) GetPlatform() *ResPlatform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ResHostSpec) GetCapacity() *ResHostResource {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *ResHostSpec) GetHttpPort() uint32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ResHostSpec) GetPeerLanAddr() string {
	if m != nil {
		return m.PeerLanAddr
	}
	return ""
}

func (m *ResHostSpec) GetPeerWanAddr() string {
	if m != nil {
		return m.PeerWanAddr
	}
	return ""
}

type ResPlatform struct {
	Os     string `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Kernel string `protobuf:"bytes,2,opt,name=kernel" json:"kernel,omitempty"`
	Arch   string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
}

func (m *ResPlatform) Reset()                    { *m = ResPlatform{} }
func (m *ResPlatform) String() string            { return proto.CompactTextString(m) }
func (*ResPlatform) ProtoMessage()               {}
func (*ResPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ResPlatform) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ResPlatform) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *ResPlatform) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ResHostResource struct {
	Memory  uint64 `protobuf:"varint,1,opt,name=memory" json:"memory,omitempty"`
	Cpu     uint64 `protobuf:"varint,2,opt,name=cpu" json:"cpu,omitempty"`
	Storage uint64 `protobuf:"varint,3,opt,name=storage" json:"storage,omitempty"`
}

func (m *ResHostResource) Reset()                    { *m = ResHostResource{} }
func (m *ResHostResource) String() string            { return proto.CompactTextString(m) }
func (*ResHostResource) ProtoMessage()               {}
func (*ResHostResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResHostResource) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *ResHostResource) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ResHostResource) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

type ResHostStatus struct {
	Phase  string `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	Uptime uint64 `protobuf:"varint,2,opt,name=uptime" json:"uptime,omitempty"`
}

func (m *ResHostStatus) Reset()                    { *m = ResHostStatus{} }
func (m *ResHostStatus) String() string            { return proto.CompactTextString(m) }
func (*ResHostStatus) ProtoMessage()               {}
func (*ResHostStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResHostStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *ResHostStatus) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

type ResZone struct {
	Meta     *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Phase    int32       `protobuf:"varint,3,opt,name=phase" json:"phase,omitempty"`
	Summary  string      `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	WanAddrs []string    `protobuf:"bytes,5,rep,name=wan_addrs,json=wanAddrs" json:"wan_addrs,omitempty"`
	LanAddrs []string    `protobuf:"bytes,6,rep,name=lan_addrs,json=lanAddrs" json:"lan_addrs,omitempty"`
	Cells    []*ResCell  `protobuf:"bytes,7,rep,name=cells" json:"cells,omitempty"`
	Options  []*Label    `protobuf:"bytes,8,rep,name=options" json:"options,omitempty"`
}

func (m *ResZone) Reset()                    { *m = ResZone{} }
func (m *ResZone) String() string            { return proto.CompactTextString(m) }
func (*ResZone) ProtoMessage()               {}
func (*ResZone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResZone) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResZone) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResZone) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ResZone) GetWanAddrs() []string {
	if m != nil {
		return m.WanAddrs
	}
	return nil
}

func (m *ResZone) GetLanAddrs() []string {
	if m != nil {
		return m.LanAddrs
	}
	return nil
}

func (m *ResZone) GetCells() []*ResCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *ResZone) GetOptions() []*Label {
	if m != nil {
		return m.Options
	}
	return nil
}

type ResCell struct {
	Meta        *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	ZoneId      string      `protobuf:"bytes,3,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Phase       int32       `protobuf:"varint,4,opt,name=phase" json:"phase,omitempty"`
	Description string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *ResCell) Reset()                    { *m = ResCell{} }
func (m *ResCell) String() string            { return proto.CompactTextString(m) }
func (*ResCell) ProtoMessage()               {}
func (*ResCell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ResCell) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResCell) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ResCell) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *ResCell) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ResZoneMasterNode struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addr   string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Action uint32 `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
}

func (m *ResZoneMasterNode) Reset()                    { *m = ResZoneMasterNode{} }
func (m *ResZoneMasterNode) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterNode) ProtoMessage()               {}
func (*ResZoneMasterNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ResZoneMasterNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResZoneMasterNode) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ResZoneMasterNode) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ResZoneMasterList struct {
	Version uint64               `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Leader  string               `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	Updated uint64               `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Items   []*ResZoneMasterNode `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *ResZoneMasterList) Reset()                    { *m = ResZoneMasterList{} }
func (m *ResZoneMasterList) String() string            { return proto.CompactTextString(m) }
func (*ResZoneMasterList) ProtoMessage()               {}
func (*ResZoneMasterList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResZoneMasterList) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResZoneMasterList) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *ResZoneMasterList) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ResZoneMasterList) GetItems() []*ResZoneMasterNode {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorMeta)(nil), "losapi.ErrorMeta")
	proto.RegisterType((*TypeMeta)(nil), "losapi.TypeMeta")
	proto.RegisterType((*ObjectMeta)(nil), "losapi.ObjectMeta")
	proto.RegisterType((*Label)(nil), "losapi.Label")
	proto.RegisterType((*ResHostOperate)(nil), "losapi.ResHostOperate")
	proto.RegisterType((*ResHost)(nil), "losapi.ResHost")
	proto.RegisterType((*ResHostList)(nil), "losapi.ResHostList")
	proto.RegisterType((*ResHostSpec)(nil), "losapi.ResHostSpec")
	proto.RegisterType((*ResPlatform)(nil), "losapi.ResPlatform")
	proto.RegisterType((*ResHostResource)(nil), "losapi.ResHostResource")
	proto.RegisterType((*ResHostStatus)(nil), "losapi.ResHostStatus")
	proto.RegisterType((*ResZone)(nil), "losapi.ResZone")
	proto.RegisterType((*ResCell)(nil), "losapi.ResCell")
	proto.RegisterType((*ResZoneMasterNode)(nil), "losapi.ResZoneMasterNode")
	proto.RegisterType((*ResZoneMasterList)(nil), "losapi.ResZoneMasterList")
	proto.RegisterEnum("losapi.OperateAction", OperateAction_name, OperateAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiZoneMaster service

type ApiZoneMasterClient interface {
	HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResZoneMasterList, error)
}

type apiZoneMasterClient struct {
	cc *grpc.ClientConn
}

func NewApiZoneMasterClient(cc *grpc.ClientConn) ApiZoneMasterClient {
	return &apiZoneMasterClient{cc}
}

func (c *apiZoneMasterClient) HostStatusSync(ctx context.Context, in *ResHost, opts ...grpc.CallOption) (*ResZoneMasterList, error) {
	out := new(ResZoneMasterList)
	err := grpc.Invoke(ctx, "/losapi.ApiZoneMaster/HostStatusSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiZoneMaster service

type ApiZoneMasterServer interface {
	HostStatusSync(context.Context, *ResHost) (*ResZoneMasterList, error)
}

func RegisterApiZoneMasterServer(s *grpc.Server, srv ApiZoneMasterServer) {
	s.RegisterService(&_ApiZoneMaster_serviceDesc, srv)
}

func _ApiZoneMaster_HostStatusSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/losapi.ApiZoneMaster/HostStatusSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiZoneMasterServer).HostStatusSync(ctx, req.(*ResHost))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiZoneMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "losapi.ApiZoneMaster",
	HandlerType: (*ApiZoneMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostStatusSync",
			Handler:    _ApiZoneMaster_HostStatusSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbtypes.proto",
}

func init() { proto.RegisterFile("pbtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xee, 0xae, 0xed, 0xb5, 0xf7, 0x58, 0x4e, 0xd3, 0x01, 0xda, 0x2d, 0xdc, 0xac, 0x2c, 0x95,
	0x44, 0x48, 0xa4, 0x74, 0xcb, 0x0d, 0x17, 0x20, 0x45, 0x08, 0x41, 0xa4, 0x94, 0x54, 0x13, 0x22,
	0x24, 0x6e, 0x56, 0x13, 0x7b, 0x20, 0x26, 0xb6, 0x67, 0x34, 0x33, 0x6e, 0xb4, 0x5c, 0xf2, 0x04,
	0xbc, 0x0f, 0x2f, 0xc0, 0x23, 0xf0, 0x0e, 0xbc, 0x04, 0x3a, 0xf3, 0xe3, 0xec, 0xae, 0x8a, 0xe8,
	0xdd, 0x7c, 0xfe, 0xce, 0x9c, 0x33, 0xe7, 0xef, 0x33, 0x14, 0xf2, 0xda, 0x6c, 0x24, 0xd7, 0x27,
	0x52, 0x09, 0x23, 0xc8, 0xac, 0x15, 0x9a, 0xc9, 0xa6, 0xfc, 0x02, 0xe6, 0xdf, 0x28, 0x25, 0xd4,
	0x2b, 0x6e, 0x18, 0x21, 0x10, 0x57, 0xa2, 0xe6, 0x8b, 0xc9, 0x72, 0x72, 0x3c, 0xa7, 0xf6, 0x4c,
	0x16, 0x90, 0x76, 0x5c, 0x6b, 0xf6, 0x0b, 0x5f, 0x4c, 0xed, 0xe7, 0x00, 0xcb, 0x6f, 0x21, 0xfb,
	0x61, 0x23, 0x79, 0xb8, 0x79, 0xdb, 0xf4, 0x75, 0xb8, 0x89, 0x67, 0x72, 0x04, 0x09, 0x47, 0xd7,
	0xf6, 0x5e, 0xbe, 0x7a, 0x74, 0xe2, 0x42, 0x9e, 0x8c, 0xf1, 0xa8, 0xe3, 0xcb, 0x1a, 0xe0, 0xe2,
	0xfa, 0x57, 0x5e, 0x19, 0xeb, 0xea, 0x00, 0xa6, 0x4d, 0x70, 0x34, 0x6d, 0x6a, 0x74, 0xdd, 0xb3,
	0x2e, 0x44, 0xb7, 0x67, 0x7c, 0x54, 0xa5, 0x38, 0x33, 0xbc, 0x5e, 0x44, 0xcb, 0xc9, 0x71, 0x4c,
	0x03, 0x44, 0x66, 0x90, 0xb5, 0x65, 0x62, 0xc7, 0x78, 0x58, 0xbe, 0x80, 0xe4, 0x9c, 0x5d, 0xf3,
	0x76, 0x74, 0x38, 0xd9, 0x72, 0xf8, 0x3e, 0x24, 0x6f, 0x58, 0x3b, 0x84, 0x28, 0x0e, 0x94, 0x7f,
	0x4d, 0xe0, 0x80, 0x72, 0xfd, 0x9d, 0xd0, 0xe6, 0x42, 0x72, 0xc5, 0x0c, 0x27, 0x8f, 0x61, 0xc6,
	0x2a, 0xd3, 0x88, 0xde, 0x5e, 0x2f, 0xa8, 0x47, 0xe4, 0x09, 0xa4, 0x15, 0x6f, 0xdb, 0x75, 0x53,
	0x7b, 0x17, 0x33, 0x84, 0x67, 0x35, 0x12, 0xbf, 0x89, 0x9e, 0x23, 0x11, 0x39, 0x02, 0xe1, 0x59,
	0x4d, 0x9e, 0x42, 0x56, 0xc9, 0x61, 0x3d, 0x68, 0xff, 0xd4, 0x88, 0xa6, 0x95, 0x1c, 0xae, 0x34,
	0xb7, 0x94, 0x62, 0x9d, 0xa3, 0x12, 0x47, 0x29, 0xd6, 0x05, 0xaa, 0xd5, 0xda, 0x51, 0x33, 0x47,
	0xb5, 0x5a, 0x5b, 0xea, 0x23, 0x98, 0x4b, 0xa1, 0x8c, 0xe3, 0xd2, 0x65, 0x74, 0x5c, 0xd0, 0x0c,
	0x3f, 0x20, 0x59, 0xfe, 0x39, 0x81, 0xd4, 0xa7, 0x42, 0x3e, 0x86, 0xb8, 0xe3, 0x86, 0xd9, 0x0c,
	0xf2, 0x15, 0x09, 0x7d, 0xb9, 0xef, 0x01, 0xb5, 0x3c, 0xf9, 0x0c, 0x52, 0xe1, 0xd2, 0xf6, 0x2d,
	0x7c, 0x1c, 0x4c, 0x77, 0x8b, 0x42, 0x83, 0x19, 0x39, 0x82, 0x58, 0x4b, 0x5e, 0xd9, 0x4c, 0xf3,
	0xd5, 0x7b, 0x7b, 0xe6, 0x97, 0x92, 0x57, 0xd4, 0x1a, 0x90, 0x4f, 0x61, 0xa6, 0x0d, 0x33, 0x83,
	0xb6, 0xa9, 0xe7, 0xab, 0x0f, 0xf6, 0x4d, 0x2d, 0x49, 0xbd, 0x51, 0xf9, 0x39, 0xe4, 0x9e, 0x38,
	0x6f, 0xb4, 0x21, 0xcf, 0x20, 0x69, 0x0c, 0xef, 0xf4, 0x62, 0xba, 0x8c, 0x8e, 0xf3, 0xd5, 0xc3,
	0xbd, 0xcb, 0xd4, 0xb1, 0xe5, 0xdf, 0x93, 0xf1, 0x1a, 0x86, 0x26, 0xcf, 0x21, 0x93, 0x2d, 0x33,
	0x3f, 0x0b, 0xd5, 0xf9, 0x84, 0xb6, 0x5f, 0xf8, 0xda, 0x53, 0x74, 0x34, 0x22, 0x2f, 0x21, 0xab,
	0x98, 0x64, 0x55, 0x63, 0x36, 0x3e, 0xa5, 0x27, 0xfb, 0xa1, 0xb8, 0x16, 0x83, 0xaa, 0x38, 0x1d,
	0x0d, 0xb1, 0x0d, 0x37, 0xc6, 0xc8, 0x35, 0x96, 0xde, 0x76, 0xaf, 0xa0, 0x19, 0x7e, 0x78, 0x2d,
	0x94, 0x21, 0x25, 0x14, 0x92, 0x73, 0xb5, 0x6e, 0x59, 0xbf, 0x66, 0x75, 0xad, 0x6c, 0x0f, 0xe7,
	0x34, 0xc7, 0x8f, 0xe7, 0xac, 0x3f, 0xad, 0x6b, 0x35, 0xda, 0xdc, 0x05, 0x9b, 0xf4, 0xde, 0xe6,
	0x47, 0x67, 0x53, 0x9e, 0xd9, 0xcc, 0xc2, 0x93, 0x71, 0x67, 0x84, 0x0e, 0x3b, 0x23, 0x34, 0x4e,
	0xe9, 0x2d, 0x57, 0x3d, 0x6f, 0xc3, 0x30, 0x3a, 0x84, 0xa3, 0xcf, 0x54, 0x75, 0xe3, 0x27, 0xd1,
	0x9e, 0xcb, 0x2b, 0x78, 0xb8, 0x97, 0x0c, 0x5e, 0xef, 0x78, 0x27, 0xd4, 0xc6, 0xba, 0x8c, 0xa9,
	0x47, 0xe4, 0x10, 0xa2, 0x4a, 0x0e, 0xd6, 0x67, 0x4c, 0xf1, 0x88, 0xeb, 0xa6, 0x8d, 0x50, 0xa8,
	0x0e, 0x7e, 0x11, 0x3d, 0x2c, 0xbf, 0x84, 0x62, 0xa7, 0x97, 0xb8, 0x62, 0xf2, 0x86, 0xe9, 0xb0,
	0x77, 0x0e, 0x60, 0xa8, 0x41, 0x9a, 0xc6, 0xef, 0x77, 0x4c, 0x3d, 0x2a, 0xff, 0x71, 0xf3, 0xfa,
	0x93, 0xe8, 0xf9, 0x38, 0xaf, 0xd3, 0xff, 0x99, 0xd7, 0x31, 0x02, 0x3e, 0x25, 0x09, 0x11, 0xf0,
	0x89, 0x43, 0xd7, 0x31, 0xb5, 0xb1, 0xb3, 0x36, 0xa7, 0x01, 0x62, 0xa7, 0x42, 0x8d, 0xf5, 0x22,
	0x59, 0x46, 0xc7, 0x73, 0x9a, 0xdd, 0xb9, 0x02, 0x6b, 0x24, 0xdb, 0x91, 0x9c, 0x39, 0xb2, 0x0d,
	0xe4, 0x33, 0x48, 0x70, 0xbd, 0xb5, 0x5d, 0xb3, 0xdd, 0x01, 0xfc, 0x9a, 0xb7, 0x2d, 0x75, 0x2c,
	0x39, 0xc2, 0x05, 0x42, 0x79, 0xd0, 0x8b, 0xcc, 0x1a, 0x16, 0xc1, 0xd0, 0x2a, 0x11, 0x0d, 0x6c,
	0xf9, 0xbb, 0xcb, 0x16, 0xef, 0xbe, 0x73, 0xb6, 0xff, 0x29, 0x2c, 0x63, 0x19, 0xe2, 0xed, 0x32,
	0x2c, 0x21, 0xaf, 0xb9, 0xae, 0x54, 0x63, 0x43, 0xda, 0xc1, 0x9c, 0xd3, 0xed, 0x4f, 0xe5, 0x05,
	0x3c, 0xf2, 0x15, 0x7f, 0xc5, 0xb4, 0xe1, 0xea, 0x7b, 0x94, 0xff, 0xb7, 0xa8, 0xb1, 0x9d, 0x49,
	0xaf, 0xc6, 0x78, 0xde, 0xd2, 0xc4, 0x68, 0x5b, 0x13, 0xcb, 0x3f, 0x26, 0x7b, 0x1e, 0xed, 0xf2,
	0x2e, 0x20, 0x7d, 0xc3, 0x95, 0x0e, 0x12, 0x1a, 0xd3, 0x00, 0xd1, 0x4f, 0xcb, 0x59, 0xcd, 0x83,
	0x77, 0x8f, 0xb6, 0x35, 0x3d, 0xda, 0xd1, 0x74, 0xf2, 0x3c, 0x08, 0x41, 0x6c, 0xcb, 0xfb, 0x74,
	0xab, 0x0f, 0xbb, 0x79, 0x78, 0x49, 0xf8, 0xe4, 0x05, 0x14, 0x5e, 0xb4, 0x4e, 0x9d, 0x6e, 0xe7,
	0x90, 0x5e, 0xf5, 0xb7, 0xbd, 0xb8, 0xeb, 0x0f, 0x1f, 0x90, 0x39, 0x24, 0x97, 0x86, 0x29, 0x73,
	0x38, 0x21, 0x19, 0xc4, 0x97, 0x46, 0xc8, 0xc3, 0xe9, 0xea, 0x02, 0x8a, 0x53, 0xd9, 0xdc, 0xbb,
	0x23, 0x5f, 0xc1, 0xc1, 0xfd, 0x58, 0x5f, 0x6e, 0xfa, 0x8a, 0xec, 0x0b, 0xd0, 0x87, 0x6f, 0x7f,
	0x08, 0xa6, 0x5f, 0x3e, 0xb8, 0x9e, 0xd9, 0x3f, 0xf0, 0xcb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xac, 0x24, 0x56, 0xcc, 0x92, 0x07, 0x00, 0x00,
}
